// Turns the model into the OpenBSD files it replaces. The Go backend
// will own the real generators; these show the user exactly what Apply
// writes and pin down the shape of the output.
import { timeoutNames, tunnels, type Endpoint, type FormRule, type Iface, type IfaceEndpoint, type Model, type NatRule, type PortForward, type Protocol, type Rule, type SelfEndpoint } from './types';
import { isFloating } from '../lib/rules';
import { netmask, network } from '../lib/ip';
import { gatewayStatus } from './live';

export interface GeneratedFile {
  path: string;
  content: string;
}

// Where a generated line came from, so the UI can link back to it.
export interface Origin {
  label: string;
  to: string;
}

export interface PfLine {
  text: string;
  origin?: Origin;
}

const header = '# Generated by OPF. Edits here are overwritten; use the web interface.';

const staticIfaces = (m: Model) => m.interfaces.filter((i) => i.enabled && i.ipv4.mode === 'static' && i.ipv4.address && i.ipv4.prefix !== undefined);

function endpoint(e: Endpoint, m: Model): string {
  const not = e.not ? '! ' : '';
  switch (e.type) {
    case 'any':
      return 'any';
    case 'self':
      return `${not}${ifaceRef(e, m)}`;
    case 'iface':
      return `${not}${ifaceRef(e, m)}`;
    case 'host':
    case 'network':
      return `${not}${e.value}`;
    case 'alias':
      return m.firewall.aliases.some((a) => a.name === e.alias && a.type !== 'ports') ? `${not}<${e.alias}>` : `${not}${e.alias}`;
  }
}

// Without parentheses pf resolves an interface once, when rules load.
export function ifaceDynamic(e: IfaceEndpoint | SelfEndpoint, m: Model): boolean {
  if (e.dynamic !== undefined) return e.dynamic;
  // self is every interface's addresses: follow them if any can change.
  if (e.type === 'self') return m.interfaces.some((i) => i.enabled && (i.ipv4.mode !== 'static' || i.ipv6 === 'slaac'));
  if (e.group) return true;
  const i = m.interfaces.find((x) => x.id === e.iface);
  return !i || i.ipv4.mode !== 'static' || i.ipv6 === 'slaac';
}

function ifaceRef(e: IfaceEndpoint | SelfEndpoint, m: Model): string {
  let ref = e.type === 'self' ? 'self' : e.iface ? `$${e.iface}` : e.group ?? '';
  if (e.part) ref += `:${e.part}`;
  if (e.noAlias) ref += ':0';
  return ifaceDynamic(e, m) ? `(${ref})` : ref;
}

function proto(p: Protocol): string {
  if (p === 'any') return '';
  if (p === 'tcp/udp') return ' proto { tcp udp }';
  return ` proto ${p}`;
}

const hasPorts = (p: Protocol) => p === 'tcp' || p === 'udp' || p === 'tcp/udp';

// Accepts pf port syntax ("443", "8000:8080", "> 1023", "!= 22"), a
// comma list, or "alias:name".
export function portExpr(spec: string | undefined, m: Model): string {
  if (!spec?.trim()) return '';
  const s = spec.trim();
  if (s.startsWith('alias:')) {
    const a = m.firewall.aliases.find((x) => x.name === s.slice(6));
    return a ? ` port { ${a.entries.join(' ')} }` : '';
  }
  if (s.includes(',')) return ` port { ${s.split(',').map((x) => x.trim()).filter(Boolean).join(' ')} }`;
  return ` port ${s.replace(/^(\d+)-(\d+)$/, '$1:$2')}`;
}

function gatewayAddr(id: string | undefined, m: Model): string | undefined {
  const g = m.routing.gateways.find((x) => x.id === id);
  if (!g) return undefined;
  return g.address === 'dhcp' ? gatewayStatus[g.id]?.address ?? '0.0.0.0' : g.address;
}

function onClause(ifaces: string[], groups: string[]): string {
  const parts = [...ifaces.map((i) => `$${i}`), ...groups];
  if (parts.length === 0) return '';
  if (parts.length === 1) return ` on ${parts[0]}`;
  return ` on { ${parts.join(' ')} }`;
}

// As pf reads quoted strings: only the quotes need escaping.
const quote = (s: string) => `"${s.replace(/"/g, '\\"')}"`;

// Rules are labelled with the model object they come from,
// "opf:<kind>:<id>", which is what pfctl reports counters by;
// descriptions are comments above them (see internal/pf/generate.go).
const labelId = /^[A-Za-z0-9_-]{1,32}$/;
export const pfLabel = (kind: 'rule' | 'forward' | 'nat' | 'auto-nat' | 'builtin' | 'split-tunnel' | 'antispoof', id: string) =>
  labelId.test(id) ? ` label ${quote(`opf:${kind}:${id}`)}` : '';

// A description as a pf.conf comment. pf continues a comment that ends
// in a backslash onto the next line.
/**
 * "Your networks" for a split-tunnel VPN device: every enabled inside
 * interface's network, every network behind a site-to-site peer, and
 * every static route's (internal/pf LocalNetworks). The device's
 * configuration sends these into the tunnel, and pf lets it reach
 * nothing else. With dynamic, a DHCP-addressed inside interface is
 * included as $id:network for pf to resolve; a device configuration
 * can only list fixed networks.
 */
export function localNetworks(m: Model, dynamic = false): string[] {
  const out = new Set<string>();
  for (const i of m.interfaces) {
    if (!i.enabled || i.role === 'wan') continue;
    if (i.ipv4.mode === 'static' && i.ipv4.address && i.ipv4.prefix !== undefined) out.add(`${network(i.ipv4.address, i.ipv4.prefix)}/${i.ipv4.prefix}`);
    else if (dynamic && i.ipv4.mode === 'dhcp') out.add(`$${i.id}:network`);
  }
  for (const t of tunnels(m)) if (t.enabled) for (const p of t.wireguard.peers) for (const n of p.networks) out.add(n);
  for (const r of m.routing.routes) if (r.enabled) out.add(r.network);
  return [...out];
}

const localTable = 'opf_local';

// Enabled tunnels with split-tunnel devices.
const splitPeers = (m: Model) =>
  tunnels(m).filter((t) => t.enabled).map((t) => ({ tunnel: t, peers: t.wireguard.peers.filter((p) => p.clientRoutes === 'split') })).filter((x) => x.peers.length);

export function pfComment(s: string): string {
  const c = s.replace(/\p{Cc}/gu, ' ').replace(/[\\ ]+$/, '');
  return c ? `# ${c}` : '';
}

export function ruleText(r: Rule, m: Model): string {
  if (r.kind === 'raw') return r.text.trim();
  return formRuleText(r, m);
}

function formRuleText(r: FormRule, m: Model): string {
  // Build the action part
  let action: string;
  if (r.action === 'reject') {
    action = 'block return';
  } else if (r.action === 'block' && r.blockReturn) {
    switch (r.blockReturn) {
      case 'return':
        action = 'block return';
        break;
      case 'return-rst':
        action = r.returnRstTtl !== undefined ? `block return-rst ttl ${r.returnRstTtl}` : 'block return-rst';
        break;
      case 'return-icmp':
        action = r.returnIcmpCode ? `block return-icmp (${r.returnIcmpCode})` : 'block return-icmp';
        break;
      case 'return-icmp6':
        action = r.returnIcmpCode ? `block return-icmp6 (${r.returnIcmpCode})` : 'block return-icmp6';
        break;
      default:
        action = 'block';
    }
  } else {
    action = r.action;
  }
  const out: string[] = [action];
  if (r.direction !== 'any') out.push(r.direction);
  if (r.log === 'on') out.push('log');
  if (r.log === 'all') out.push('log (all)');
  if (r.quick) out.push('quick');
  let s = out.join(' ') + onClause(r.interfaces, r.groups ?? []);
  if (r.family !== 'any') s += ` ${r.family}`;
  s += proto(r.protocol);

  const sp = hasPorts(r.protocol) ? portExpr(r.sourcePort, m) : '';
  const dp = hasPorts(r.protocol) ? portExpr(r.port, m) : '';
  if (r.source.type === 'any' && r.destination.type === 'any' && !sp && !dp && !r.osFingerprint) {
    s += ' all';
  } else {
    s += ` from ${endpoint(r.source, m)}${sp}`;
    if (r.osFingerprint) s += ` os ${quote(r.osFingerprint)}`;
    s += ` to ${endpoint(r.destination, m)}${dp}`;
  }

  if ((r.protocol === 'tcp' || r.protocol === 'tcp/udp') && r.tcpFlags && r.tcpFlags !== 'S/SA') s += ` flags ${r.tcpFlags}`;
  if ((r.protocol === 'icmp' || r.protocol === 'icmp6') && r.icmpType) s += ` ${r.protocol === 'icmp6' ? 'icmp6-type' : 'icmp-type'} ${r.icmpType}`;
  if (r.tagged) s += ` tagged ${r.tagged}`;
  if (r.tag) s += ` tag ${r.tag}`;
  if (r.probability !== undefined && r.probability < 100) s += ` probability ${r.probability}%`;
  if (r.once) s += ' once';

  const st = r.state;
  if (st && r.action === 'pass') {
    if (st.mode === 'none') {
      s += ' no state';
    } else {
      const opts: string[] = [];
      if (st.maxStates) opts.push(`max ${st.maxStates}`);
      if (st.maxSrcConn) opts.push(`max-src-conn ${st.maxSrcConn}`);
      if (st.maxSrcConnRate) opts.push(`max-src-conn-rate ${st.maxSrcConnRate.count}/${st.maxSrcConnRate.seconds}`);
      if (st.overload) opts.push(`overload <${st.overload}>${st.flushGlobal ? ' flush global' : ''}`);
      if (st.sloppy) opts.push('sloppy');
      if (st.policy) opts.push(st.policy);
      const kw = st.mode === 'modulate' ? 'modulate state' : st.mode === 'synproxy' ? 'synproxy state' : 'keep state';
      if (opts.length || st.mode !== 'keep') s += ` ${kw}${opts.length ? ` (${opts.join(', ')})` : ''}`;
    }
  }
  if (r.prio !== undefined) s += ` set prio ${r.prio}`;
  if (r.rtable !== undefined) s += ` rtable ${r.rtable}`;
  const rt = gatewayAddr(r.gateway, m);
  if (rt) s += ` route-to ${rt}`;
  const rp = gatewayAddr(r.replyTo, m);
  if (rp) s += ` reply-to ${rp}`;
  return s + pfLabel('rule', r.id);
}

// Exceptions tag their traffic and nat-to rules on the same interface
// skip it; see NoNATTag in internal/pf.
const noNatTag = 'opf_nonat';
const natExceptions = (m: Model, iface: string) =>
  m.firewall.outboundNat.mode !== 'auto' && m.firewall.outboundNat.rules.some((n) => n.enabled && n.iface === iface && n.translation.type === 'none');

export function natText(n: NatRule, m: Model, label = pfLabel('nat', n.id)): string {
  const hosts = `on $${n.iface} inet from ${endpoint(n.source, m)} to ${endpoint(n.destination, m)}`;
  if (n.translation.type === 'none') return `match out ${hosts} tag ${noNatTag}${label}`;
  let s = `match out ${hosts}`;
  if (natExceptions(m, n.iface)) s += ` ! tagged ${noNatTag}`;
  s += ` nat-to ${n.translation.type === 'ifaddr' ? `($${n.iface}:0)` : n.translation.value}`;
  if (n.pool) s += ` ${n.pool}`;
  if (n.staticPort) s += ' static-port';
  return s + label;
}

// The NAT rules OPF adds on its own: every internal network leaves
// each WAN translated to that WAN's address.
export function automaticNat(m: Model): NatRule[] {
  const wans = m.interfaces.filter((i) => i.enabled && i.role === 'wan');
  // Every inside network, however it's addressed.
  return wans.flatMap((w) =>
    m.interfaces
      .filter((i) => i.enabled && i.role !== 'wan' && i.ipv4.mode !== 'none')
      .map((i) => ({
        id: `auto-${w.id}-${i.id}`, enabled: true, iface: w.id, source: { type: 'iface', iface: i.id, part: 'network' } as Endpoint,
        destination: { type: 'any' } as Endpoint, translation: { type: 'ifaddr' } as const, staticPort: false,
        description: `Automatic: ${i.name} to ${w.name}`,
      })),
  );
}

export function forwardText(f: PortForward, m: Model): string[] {
  const log = f.log ? ' log' : '';
  const from = endpoint(f.source, m);
  // Same interface references as user rules; nat-to targets stay in
  // parentheses, as pf.conf(5) advises for NAT.
  const pub = endpoint({ type: 'iface', iface: f.iface }, m);
  const label = pfLabel('forward', f.id);
  const lines = [
    `pass in${log} quick on $${f.iface}${proto(f.protocol)} from ${from} to ${pub} port ${f.externalPort} rdr-to ${f.target} port ${f.targetPort}${label}`,
  ];
  if (f.reflection) {
    const inside = m.interfaces.filter((i) => i.enabled && (i.role === 'lan' || i.role === 'opt') && i.ipv4.mode !== 'none');
    for (const i of inside) {
      const net = endpoint({ type: 'iface', iface: i.id, part: 'network' }, m);
      lines.push(`pass in quick on $${i.id}${proto(f.protocol)} from ${net} to ${pub} port ${f.externalPort} rdr-to ${f.target} port ${f.targetPort}${label}`);
      lines.push(`match out on $${i.id}${proto(f.protocol)} from ${net} to ${f.target} port ${f.targetPort} nat-to ($${i.id})${label}`);
    }
  }
  return lines;
}


export function pfRuleset(m: Model): PfLine[] {
  const L: PfLine[] = [];
  const add = (text: string, origin?: Origin) => L.push({ text, origin });
  const blank = () => L.push({ text: '' });
  // An object's rules, with its description above them.
  const described = (description: string, origin: Origin, ...rules: string[]) => {
    const c = pfComment(description);
    if (c) add(c, origin);
    for (const r of rules) add(r, origin);
  };
  const fw = m.firewall;
  const o = fw.options;
  const ifaces = m.interfaces.filter((i) => i.enabled);
  const wan = ifaces.find((i) => i.role === 'wan');
  const lan = ifaces.find((i) => i.role === 'lan');
  // The custom pf editor is a drawer on the Ruleset page.
  const custom: Origin = { label: 'Custom pf', to: '/firewall/ruleset?edit=custom' };

  add(header);
  blank();
  add('# Interfaces');
  for (const i of ifaces) add(`${i.id} = "${i.device}"`, { label: `Interface ${i.name}`, to: `/interfaces/${i.id}` });
  blank();

  add('# Aliases');
  for (const a of fw.aliases.filter((x) => x.type !== 'ports')) {
    const origin = { label: `Alias ${a.name}`, to: '/firewall/aliases' };
    if (a.type === 'table') add(`table <${a.name}> persist`, origin);
    else if (a.type === 'url') add(`table <${a.name}> persist file "/var/opf/tables/${a.name}"\t# refreshed every ${a.refreshHours ?? 24}h from ${a.url}`, origin);
    else add(`table <${a.name}> const { ${a.entries.join(' ')} }`, origin);
  }
  if (wan?.blockBogons) add('table <bogons> const { 0.0.0.0/8 100.64.0.0/10 127.0.0.0/8 169.254.0.0/16 192.0.0.0/24 198.18.0.0/15 224.0.0.0/3 }', { label: 'WAN protection', to: `/interfaces/${wan.id}` });
  if (wan?.blockPrivate) add('table <private> const { 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16 }', { label: 'WAN protection', to: `/interfaces/${wan.id}` });
  const split = splitPeers(m);
  if (split.length) add(`table <${localTable}> const { ${localNetworks(m, true).join(' ')} }`, { label: 'WireGuard: your networks', to: '/services/wireguard' });
  blank();

  // Options, in pf.conf(5)'s order; each links to its setting.
  add('# Options');
  const opt = (what: string, line: string) => add(line, { label: `Firewall settings: ${what}`, to: '/firewall/settings' });
  const braced = (items: string[]) => (items.length === 1 ? items[0] : `{ ${items.join(', ')} }`);
  opt('Blocked traffic', `set block-policy ${o.blockPolicy}`);
  opt('Connection tracking', `set state-policy ${o.statePolicy}`);
  opt('Timeouts', `set optimization ${o.optimization}`);
  if (o.rulesetOptimization) opt('Ruleset optimization', `set ruleset-optimization ${o.rulesetOptimization}`);
  const lim = o.limits ?? {};
  const limits = [`states ${o.maxStates}`, ...([['src-nodes', lim.srcNodes], ['frags', lim.frags], ['tables', lim.tables], ['table-entries', lim.tableEntries], ['pktdelay_pkts', lim.pktdelayPkts], ['anchors', lim.anchors]] as const)
    .filter(([, n]) => n !== undefined).map(([k, n]) => `${k} ${n}`)];
  opt('Limits', `set limit ${braced(limits)}`);
  const timeouts = timeoutNames.filter((k) => o.timeouts?.[k] !== undefined).map((k) => `${k} ${o.timeouts![k]}`);
  if (timeouts.length) opt('Timeouts', `set timeout ${braced(timeouts)}`);
  opt('SYN cookies', `set syncookies ${o.syncookies}${o.syncookies === 'adaptive' ? ` (start ${o.syncookiesStart ?? 25}%, end ${o.syncookiesEnd ?? 12}%)` : ''}`);
  if (o.stateDefaults?.length) opt('State defaults', `set state-defaults ${o.stateDefaults.join(', ')}`);
  if (o.reassemble) opt('Fragment reassembly', `set reassemble ${o.reassemble}${o.reassemble === 'yes' && o.reassembleNoDf ? ' no-df' : ''}`);
  if (o.debug) opt('Debug level', `set debug ${o.debug}`);
  if (o.hostId !== undefined) opt('Host id', `set hostid ${o.hostId}`);
  if (o.fingerprints) opt('OS fingerprints', `set fingerprints ${quote(o.fingerprints)}`);
  const skip = ['lo', ...(o.skipOn ?? []).map((x) => (m.interfaces.some((i) => i.id === x) ? `$${x}` : x))];
  opt('Unfiltered interfaces', skip.length === 1 ? 'set skip on lo' : `set skip on { ${skip.join(' ')} }`);
  if (o.logInterface === 'none') opt('Statistics interface', 'set loginterface none');
  else if (o.logInterface) opt('Statistics interface', `set loginterface $${o.logInterface}`);
  else if (wan) opt('Statistics interface', `set loginterface $${wan.id}`);
  for (const l of fw.custom.options.split('\n').filter((x) => x.trim())) add(l, custom);
  // scrub takes a list of options; with none there's nothing to say.
  const sc = [o.scrub.noDf && 'no-df', o.scrub.randomId && 'random-id', o.scrub.minTtl && `min-ttl ${o.scrub.minTtl}`, o.scrub.maxMss && `max-mss ${o.scrub.maxMss}`, o.scrub.reassembleTcp && 'reassemble tcp'].filter(Boolean);
  if (o.scrub.enabled && sc.length) opt('Packet normalization', `match in all scrub (${sc.join(' ')})`);
  blank();

  add('# Outbound NAT');
  const natOrigin: Origin = { label: 'Outbound NAT', to: '/firewall/nat/outbound' };
  const manual = fw.outboundNat.mode === 'auto' ? [] : fw.outboundNat.rules.filter((r) => r.enabled);
  const auto = fw.outboundNat.mode === 'manual' ? [] : automaticNat(m);
  // Exceptions first, since they end evaluation. Among match rules the
  // last nat-to wins, so manual rules follow the automatic ones.
  for (const n of manual.filter((x) => x.translation.type === 'none')) described(n.description, natOrigin, natText(n, m));
  for (const n of auto) described(n.description, natOrigin, natText(n, m, pfLabel('auto-nat', n.source.type === 'iface' ? n.source.iface ?? '' : '')));
  for (const n of manual.filter((x) => x.translation.type !== 'none')) described(n.description, natOrigin, natText(n, m));
  blank();

  add('# Defaults');
  add((o.logDefaultBlock ? 'block log all' : 'block all') + pfLabel('builtin', 'default-block'), { label: 'Default block', to: '/firewall/settings' });
  // Not quick, so outbound user rules are still reached (see internal/pf).
  add('pass out inet' + pfLabel('builtin', 'self-out'), { label: 'This firewall’s own traffic', to: '/firewall/settings' });
  add('pass out inet6' + pfLabel('builtin', 'self-out'), { label: 'This firewall’s own traffic', to: '/firewall/settings' });
  if (lan) described('Anti-lockout: the web UI and SSH stay reachable from the LAN', { label: 'Anti-lockout', to: `/interfaces/${lan.id}` },
    `pass in quick on $${lan.id} proto tcp to ${endpoint({ type: 'iface', iface: lan.id }, m)} port { 443 22 }${pfLabel('builtin', 'anti-lockout')}`);
  for (const i of ifaces.filter((x) => x.antispoof)) {
    described(`Antispoof: nothing from ${i.name}'s network arrives anywhere else`, { label: `Antispoof: ${i.name}`, to: `/interfaces/${i.id}` },
      `antispoof log quick for $${i.id} inet${pfLabel('antispoof', i.id)}`);
  }
  if (wan?.blockPrivate) described('Block private networks', { label: 'WAN protection', to: `/interfaces/${wan.id}` },
    `block in log quick on $${wan.id} from <private>${pfLabel('builtin', 'block-private')}`);
  if (wan?.blockBogons) described('Block bogon networks', { label: 'WAN protection', to: `/interfaces/${wan.id}` },
    `block in log quick on $${wan.id} from <bogons>${pfLabel('builtin', 'block-bogons')}`);
  blank();

  // Devices told to send only local traffic through their tunnel may
  // only reach local networks, whatever their own configuration says;
  // before every user rule, so no pass rule can widen it.
  if (split.length) {
    add('# WireGuard devices limited to your networks');
    for (const { tunnel: t, peers } of split) {
      const from = peers.length === 1 ? peers[0].address : `{ ${peers.map((p) => p.address).join(' ')} }`;
      described(`${t.name}: ${peers.map((p) => p.name).join(', ')}`, { label: `WireGuard: ${t.name}`, to: `/services/wireguard/${t.id}` },
        `block in log quick on $${t.id} inet from ${from} to ! <${localTable}>${pfLabel('split-tunnel', t.id)}`);
    }
    blank();
  }

  const forwards = fw.forwards.filter((f) => f.enabled && ifaces.some((i) => i.id === f.iface));
  if (forwards.length) {
    add('# Port forwards');
    for (const f of forwards) described(f.description, { label: `Port forward: ${f.description}`, to: '/firewall/nat' }, ...forwardText(f, m));
    blank();
  }

  if (fw.custom.beforeFilter.trim()) {
    add('# Custom rules (before)');
    for (const l of fw.custom.beforeFilter.split('\n')) add(l, custom);
    blank();
  }

  const floating = fw.rules.filter((r) => r.enabled && isFloating(r));
  if (floating.length) {
    add('# Floating rules');
    for (const r of floating) described(r.description, { label: `Rule: ${r.description}`, to: '/firewall/rules/floating' }, ruleText(r, m));
    blank();
  }
  for (const i of ifaces) {
    const rules = fw.rules.filter((r) => r.enabled && !isFloating(r) && r.interfaces[0] === i.id);
    if (!rules.length) continue;
    add(`# ${i.name} rules`);
    for (const r of rules) described(r.description, { label: `Rule: ${r.description}`, to: `/firewall/rules/${i.id}` }, ruleText(r, m));
    blank();
  }

  if (fw.custom.afterFilter.trim()) {
    add('# Custom rules (after)');
    for (const l of fw.custom.afterFilter.split('\n')) add(l, custom);
    blank();
  }
  return L;
}

export const pfConf = (m: Model) => pfRuleset(m).map((l) => l.text).join('\n');

function hostnameIf(i: Iface, m: Model): string {
  const lines: string[] = [header];
  if (i.vlan) lines.push(`vnetid ${i.vlan.tag} parent ${i.vlan.parent}`);
  const wg = i.wireguard;
  if (i.role === 'vpn' && wg) {
    lines.push('wgkey <private key stored by OPF>', `wgport ${wg.listenPort}`);
    for (const p of wg.peers) {
      const aips = [p.address, ...p.networks].map((a) => `wgaip ${a}`).join(' ');
      lines.push(`wgpeer ${p.publicKey} ${aips}${p.endpoint ? ` wgendpoint ${p.endpoint.replace(':', ' ')}` : ''}${p.keepalive ? ` wgpka ${p.keepalive}` : ''} wgdescr "${p.name}"`);
    }
  }
  lines.push(`description "${i.name}"`);
  if (i.mtu) lines.push(`mtu ${i.mtu}`);
  if (i.ipv4.mode === 'dhcp') lines.push('inet autoconf');
  if (i.ipv4.mode === 'static' && i.ipv4.address) lines.push(`inet ${i.ipv4.address}/${i.ipv4.prefix}`);
  if (i.ipv6 === 'slaac') lines.push('inet6 autoconf');
  lines.push(i.enabled ? 'up' : 'down');
  // Static routes whose gateway is reached through this interface.
  for (const r of m.routing.routes.filter((x) => x.enabled)) {
    const g = m.routing.gateways.find((x) => x.id === r.gateway);
    if (g?.iface === i.id && g.address !== 'dhcp') lines.push(`!route -q add -net ${r.network} ${g.address}\t# ${r.description}`);
  }
  return lines.join('\n') + '\n';
}

function dhcpdConf(m: Model): string {
  const lines: string[] = [header, '', `option domain-name "${m.system.domain}";`, ''];
  for (const s of m.dhcp) {
    const i = m.interfaces.find((x) => x.id === s.iface);
    if (!s.enabled || !i || i.ipv4.mode !== 'static' || !i.ipv4.address || i.ipv4.prefix === undefined) continue;
    const dns = s.dns === 'self' ? i.ipv4.address : s.dnsServers.join(', ');
    lines.push(`# ${i.name}`);
    lines.push(`subnet ${network(i.ipv4.address, i.ipv4.prefix)} netmask ${netmask(i.ipv4.prefix)} {`);
    lines.push(`\toption routers ${i.ipv4.address};`);
    lines.push(`\toption domain-name-servers ${dns};`);
    lines.push(`\trange ${s.rangeStart} ${s.rangeEnd};`);
    lines.push(`\tdefault-lease-time ${s.leaseHours * 3600};`);
    for (const r of s.reservations) lines.push(`\thost ${r.hostname} {`, `\t\thardware ethernet ${r.mac};`, `\t\tfixed-address ${r.ip};`, '\t}');
    lines.push('}', '');
  }
  return lines.join('\n');
}

function unboundConf(m: Model): string {
  const d = m.dns;
  const inside = staticIfaces(m).filter((i) => i.role !== 'wan');
  const lines: string[] = [header, '', 'server:', '\tinterface: 127.0.0.1'];
  for (const i of inside) lines.push(`\tinterface: ${i.ipv4.address}`);
  lines.push('\taccess-control: 127.0.0.0/8 allow');
  for (const i of inside) lines.push(`\taccess-control: ${network(i.ipv4.address!, i.ipv4.prefix!)}/${i.ipv4.prefix} allow`);
  lines.push('\thide-identity: yes', '\thide-version: yes');
  if (d.dnssec) lines.push('\tauto-trust-anchor-file: "/var/unbound/db/root.key"', '\tval-log-level: 2');
  lines.push(`\tlocal-zone: "${m.system.domain}." static`);
  for (const o of d.overrides) lines.push(`\tlocal-data: "${o.host}.${o.domain}. IN A ${o.ip}"`);
  if (d.registerReservations) for (const s of m.dhcp) for (const r of s.reservations) lines.push(`\tlocal-data: "${r.hostname}.${m.system.domain}. IN A ${r.ip}"`);
  if (d.registerDynamicLeases) lines.push('', 'remote-control:', '\tcontrol-enable: yes', '\tcontrol-interface: /var/run/unbound.sock');
  if (d.mode === 'forward') {
    lines.push('', 'forward-zone:', '\tname: "."');
    if (d.forwardTls) lines.push('\tforward-tls-upstream: yes');
    for (const f of d.forwarders) lines.push(`\tforward-addr: ${f}${d.forwardTls ? '@853' : ''}`);
  }
  return lines.join('\n') + '\n';
}

// /etc/rc.conf.local: which daemons OPF runs, and their flags. On a
// real system OPF sets only these lines and keeps the file's others
// (internal/pf MergeRcConfLocal); the preview has no other lines.
function rcConfLocal(m: Model): string {
  const devices = m.dhcp
    .filter((s) => s.enabled)
    .flatMap((s) => m.interfaces.filter((i) => i.id === s.iface && i.enabled && i.ipv4.mode === 'static' && i.ipv4.address && i.ipv4.prefix !== undefined))
    .map((i) => i.device);
  return `# Set by OPF from its web interface; the lines above are kept as they are.\ndhcpd_flags="${devices.length ? devices.join(' ') : 'NO'}"\nunbound_flags="${m.dns.enabled ? '' : 'NO'}"\n`;
}

export function generateFiles(m: Model): GeneratedFile[] {
  const files: GeneratedFile[] = [
    { path: '/etc/myname', content: `${m.system.hostname}.${m.system.domain}\n` },
    { path: '/etc/ntpd.conf', content: header + '\n' + m.system.ntpServers.map((s) => `servers ${s}`).join('\n') + '\n' },
    { path: '/etc/pf.conf', content: pfConf(m) },
    { path: '/etc/dhcpd.conf', content: dhcpdConf(m) },
    { path: '/var/unbound/etc/unbound.conf', content: unboundConf(m) },
    { path: '/etc/rc.conf.local', content: rcConfLocal(m) },
  ];
  const def = m.routing.gateways.find((g) => g.id === m.routing.defaultGateway);
  if (def && def.address !== 'dhcp') files.push({ path: '/etc/mygate', content: `${def.address}\n` });
  for (const i of m.interfaces) files.push({ path: `/etc/hostname.${i.device}`, content: hostnameIf(i, m) });
  return files;
}
