// Turns the model into the OpenBSD files it replaces. The Go backend
// will own the real generators; these show the user exactly what Apply
// writes and pin down the shape of the output.
import type { Endpoint, FormRule, Iface, Model, NatRule, PortForward, Protocol, Rule } from './types';
import { netmask, network } from '../lib/ip';
import { gatewayStatus } from './live';

export interface GeneratedFile {
  path: string;
  content: string;
}

// Where a generated line came from, so the UI can link back to it.
export interface Origin {
  label: string;
  to: string;
}

export interface PfLine {
  text: string;
  origin?: Origin;
}

const header = '# Generated by OPF. Edits here are overwritten; use the web interface.';

const staticIfaces = (m: Model) => m.interfaces.filter((i) => i.enabled && i.ipv4.mode === 'static' && i.ipv4.address && i.ipv4.prefix !== undefined);

function endpoint(e: Endpoint, m: Model): string {
  const not = e.not ? '! ' : '';
  switch (e.type) {
    case 'any':
      return 'any';
    case 'self':
      return `${not}self`;
    case 'net':
      return `${not}$${e.iface}:network`;
    case 'ifaddr':
      return `${not}($${e.iface})`;
    case 'host':
    case 'network':
      return `${not}${e.value}`;
    case 'alias':
      return m.firewall.aliases.some((a) => a.name === e.alias && a.type !== 'ports') ? `${not}<${e.alias}>` : `${not}${e.alias}`;
  }
}

function proto(p: Protocol): string {
  if (p === 'any') return '';
  if (p === 'tcp/udp') return ' proto { tcp udp }';
  return ` proto ${p}`;
}

const hasPorts = (p: Protocol) => p === 'tcp' || p === 'udp' || p === 'tcp/udp';

// Accepts pf port syntax ("443", "8000:8080", "> 1023", "!= 22"), a
// comma list, or "alias:name".
export function portExpr(spec: string | undefined, m: Model): string {
  if (!spec?.trim()) return '';
  const s = spec.trim();
  if (s.startsWith('alias:')) {
    const a = m.firewall.aliases.find((x) => x.name === s.slice(6));
    return a ? ` port { ${a.entries.join(' ')} }` : '';
  }
  if (s.includes(',')) return ` port { ${s.split(',').map((x) => x.trim()).filter(Boolean).join(' ')} }`;
  return ` port ${s.replace(/^(\d+)-(\d+)$/, '$1:$2')}`;
}

function gatewayAddr(id: string | undefined, m: Model): string | undefined {
  const g = m.routing.gateways.find((x) => x.id === id);
  if (!g) return undefined;
  return g.address === 'dhcp' ? gatewayStatus[g.id]?.address ?? '0.0.0.0' : g.address;
}

function onClause(ifaces: string[]): string {
  if (ifaces.length === 0) return '';
  if (ifaces.length === 1) return ` on $${ifaces[0]}`;
  return ` on { ${ifaces.map((i) => `$${i}`).join(' ')} }`;
}

const quote = (s: string) => `"${s.replace(/"/g, "'")}"`;

export function ruleText(r: Rule, m: Model): string {
  if (r.kind === 'raw') return r.text.trim();
  return formRuleText(r, m);
}

function formRuleText(r: FormRule, m: Model): string {
  // Build the action part
  let action: string;
  if (r.action === 'reject') {
    action = 'block return';
  } else if (r.action === 'block' && r.blockReturn) {
    switch (r.blockReturn) {
      case 'return':
        action = 'block return';
        break;
      case 'return-rst':
        action = r.returnRstTtl !== undefined ? `block return-rst ttl ${r.returnRstTtl}` : 'block return-rst';
        break;
      case 'return-icmp':
        action = r.returnIcmpCode ? `block return-icmp (${r.returnIcmpCode})` : 'block return-icmp';
        break;
      case 'return-icmp6':
        action = r.returnIcmpCode ? `block return-icmp6 (${r.returnIcmpCode})` : 'block return-icmp6';
        break;
      default:
        action = 'block';
    }
  } else {
    action = r.action;
  }
  const out: string[] = [action];
  if (r.direction !== 'any') out.push(r.direction);
  if (r.log === 'on') out.push('log');
  if (r.log === 'all') out.push('log (all)');
  if (r.quick) out.push('quick');
  let s = out.join(' ') + onClause(r.interfaces);
  if (r.family !== 'any') s += ` ${r.family}`;
  s += proto(r.protocol);

  const sp = hasPorts(r.protocol) ? portExpr(r.sourcePort, m) : '';
  const dp = hasPorts(r.protocol) ? portExpr(r.port, m) : '';
  if (r.source.type === 'any' && r.destination.type === 'any' && !sp && !dp && !r.osFingerprint) {
    s += ' all';
  } else {
    s += ` from ${endpoint(r.source, m)}${sp}`;
    if (r.osFingerprint) s += ` os ${quote(r.osFingerprint)}`;
    s += ` to ${endpoint(r.destination, m)}${dp}`;
  }

  if ((r.protocol === 'tcp' || r.protocol === 'tcp/udp') && r.tcpFlags && r.tcpFlags !== 'S/SA') s += ` flags ${r.tcpFlags}`;
  if ((r.protocol === 'icmp' || r.protocol === 'icmp6') && r.icmpType) s += ` ${r.protocol === 'icmp6' ? 'icmp6-type' : 'icmp-type'} ${r.icmpType}`;
  if (r.tagged) s += ` tagged ${r.tagged}`;
  if (r.tag) s += ` tag ${r.tag}`;
  if (r.probability !== undefined && r.probability < 100) s += ` probability ${r.probability}%`;
  if (r.once) s += ' once';

  const st = r.state;
  if (st && r.action === 'pass') {
    if (st.mode === 'none') {
      s += ' no state';
    } else {
      const opts: string[] = [];
      if (st.maxStates) opts.push(`max ${st.maxStates}`);
      if (st.maxSrcConn) opts.push(`max-src-conn ${st.maxSrcConn}`);
      if (st.maxSrcConnRate) opts.push(`max-src-conn-rate ${st.maxSrcConnRate.count}/${st.maxSrcConnRate.seconds}`);
      if (st.overload) opts.push(`overload <${st.overload}>${st.flushGlobal ? ' flush global' : ''}`);
      if (st.sloppy) opts.push('sloppy');
      if (st.policy) opts.push(st.policy);
      const kw = st.mode === 'modulate' ? 'modulate state' : st.mode === 'synproxy' ? 'synproxy state' : 'keep state';
      if (opts.length || st.mode !== 'keep') s += ` ${kw}${opts.length ? ` (${opts.join(', ')})` : ''}`;
    }
  }
  if (r.prio !== undefined) s += ` set prio ${r.prio}`;
  if (r.rtable !== undefined) s += ` rtable ${r.rtable}`;
  const rt = gatewayAddr(r.gateway, m);
  if (rt) s += ` route-to ${rt}`;
  const rp = gatewayAddr(r.replyTo, m);
  if (rp) s += ` reply-to ${rp}`;
  if (r.description) s += ` label ${quote(r.description)}`;
  return s;
}

export function natText(n: NatRule, m: Model): string {
  const hosts = `on $${n.iface} inet from ${endpoint(n.source, m)} to ${endpoint(n.destination, m)}`;
  // An exception has to stop evaluation before any nat-to applies.
  if (n.translation.type === 'none') return `pass out quick ${hosts} label ${quote(n.description)}`;
  let s = `match out ${hosts}`;
  s += ` nat-to ${n.translation.type === 'ifaddr' ? `($${n.iface}:0)` : n.translation.value}`;
  if (n.pool) s += ` ${n.pool}`;
  if (n.staticPort) s += ' static-port';
  return `${s} label ${quote(n.description)}`;
}

// The NAT rules OPF adds on its own: every internal network leaves
// each WAN translated to that WAN's address.
export function automaticNat(m: Model): NatRule[] {
  const wans = m.interfaces.filter((i) => i.enabled && i.role === 'wan');
  return wans.flatMap((w) =>
    staticIfaces(m)
      .filter((i) => i.role !== 'wan')
      .map((i) => ({
        id: `auto-${w.id}-${i.id}`, enabled: true, iface: w.id, source: { type: 'net', iface: i.id } as Endpoint,
        destination: { type: 'any' } as Endpoint, translation: { type: 'ifaddr' } as const, staticPort: false,
        description: `Automatic: ${i.name} to ${w.name}`,
      })),
  );
}

export function forwardText(f: PortForward, m: Model): string[] {
  const log = f.log ? ' log' : '';
  const from = endpoint(f.source, m);
  const lines = [
    `pass in${log} quick on $${f.iface}${proto(f.protocol)} from ${from} to ($${f.iface}) port ${f.externalPort} rdr-to ${f.target} port ${f.targetPort} label ${quote(f.description)}`,
  ];
  if (f.reflection) {
    const inside = staticIfaces(m).filter((i) => i.role === 'lan' || i.role === 'opt');
    for (const i of inside) {
      lines.push(`pass in quick on $${i.id}${proto(f.protocol)} from $${i.id}:network to ($${f.iface}) port ${f.externalPort} rdr-to ${f.target} port ${f.targetPort}`);
      lines.push(`match out on $${i.id}${proto(f.protocol)} from $${i.id}:network to ${f.target} port ${f.targetPort} nat-to ($${i.id})`);
    }
  }
  return lines;
}

const isFloating = (r: Rule) => r.interfaces.length !== 1;

export function pfRuleset(m: Model): PfLine[] {
  const L: PfLine[] = [];
  const add = (text: string, origin?: Origin) => L.push({ text, origin });
  const blank = () => L.push({ text: '' });
  const fw = m.firewall;
  const o = fw.options;
  const ifaces = m.interfaces.filter((i) => i.enabled);
  const wan = ifaces.find((i) => i.role === 'wan');
  const lan = ifaces.find((i) => i.role === 'lan');
  const settings: Origin = { label: 'Firewall settings', to: '/firewall/settings' };
  const custom: Origin = { label: 'Custom pf', to: '/firewall/ruleset' };

  add(header);
  blank();
  add('# Interfaces');
  for (const i of ifaces) add(`${i.id} = "${i.device}"`, { label: `Interface ${i.name}`, to: `/interfaces/${i.id}` });
  blank();

  add('# Aliases');
  for (const a of fw.aliases.filter((x) => x.type !== 'ports')) {
    const origin = { label: `Alias ${a.name}`, to: '/firewall/aliases' };
    if (a.type === 'table') add(`table <${a.name}> persist`, origin);
    else if (a.type === 'url') add(`table <${a.name}> persist file "/var/opf/tables/${a.name}"\t# refreshed every ${a.refreshHours ?? 24}h from ${a.url}`, origin);
    else add(`table <${a.name}> const { ${a.entries.join(' ')} }`, origin);
  }
  if (wan?.blockBogons) add('table <bogons> const { 0.0.0.0/8 100.64.0.0/10 127.0.0.0/8 169.254.0.0/16 192.0.0.0/24 198.18.0.0/15 224.0.0.0/3 }', { label: 'WAN protection', to: `/interfaces/${wan.id}` });
  if (wan?.blockPrivate) add('table <private> const { 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16 }', { label: 'WAN protection', to: `/interfaces/${wan.id}` });
  blank();

  add('# Options');
  add(`set block-policy ${o.blockPolicy}`, settings);
  add(`set state-policy ${o.statePolicy}`, settings);
  add(`set optimization ${o.optimization}`, settings);
  add(`set limit states ${o.maxStates}`, settings);
  add(`set syncookies ${o.syncookies}${o.syncookies === 'adaptive' ? ' (start 25%, end 12%)' : ''}`, settings);
  add('set skip on lo', settings);
  if (wan) add(`set loginterface $${wan.id}`, settings);
  for (const l of fw.custom.options.split('\n').filter((x) => x.trim())) add(l, custom);
  if (o.scrub.enabled) {
    const sc = [o.scrub.noDf && 'no-df', o.scrub.randomId && 'random-id', o.scrub.maxMss && `max-mss ${o.scrub.maxMss}`].filter(Boolean).join(' ');
    add(`match in all scrub (${sc})`, settings);
  }
  blank();

  add('# Outbound NAT');
  const natOrigin: Origin = { label: 'Outbound NAT', to: '/firewall/nat/outbound' };
  const manual = fw.outboundNat.mode === 'auto' ? [] : fw.outboundNat.rules.filter((r) => r.enabled);
  const auto = fw.outboundNat.mode === 'manual' ? [] : automaticNat(m);
  // Exceptions first, since they end evaluation. Among match rules the
  // last nat-to wins, so manual rules follow the automatic ones.
  for (const n of manual.filter((x) => x.translation.type === 'none')) add(natText(n, m), natOrigin);
  for (const n of auto) add(natText(n, m), natOrigin);
  for (const n of manual.filter((x) => x.translation.type !== 'none')) add(natText(n, m), natOrigin);
  blank();

  add('# Defaults');
  add(o.logDefaultBlock ? 'block log all' : 'block all', { label: 'Default block', to: '/firewall/settings' });
  add('pass out quick inet', { label: 'This firewall’s own traffic', to: '/firewall/settings' });
  add('pass out quick inet6', { label: 'This firewall’s own traffic', to: '/firewall/settings' });
  if (lan) add(`pass in quick on $${lan.id} proto tcp to ($${lan.id}) port { 443 22 } label "Anti-lockout"`, { label: 'Anti-lockout', to: `/interfaces/${lan.id}` });
  if (wan?.blockPrivate) add(`block in log quick on $${wan.id} from <private> label "Block private networks"`, { label: 'WAN protection', to: `/interfaces/${wan.id}` });
  if (wan?.blockBogons) add(`block in log quick on $${wan.id} from <bogons> label "Block bogon networks"`, { label: 'WAN protection', to: `/interfaces/${wan.id}` });
  blank();

  const forwards = fw.forwards.filter((f) => f.enabled && ifaces.some((i) => i.id === f.iface));
  if (forwards.length) {
    add('# Port forwards');
    for (const f of forwards) for (const t of forwardText(f, m)) add(t, { label: `Port forward: ${f.description}`, to: '/firewall/nat' });
    blank();
  }

  if (fw.custom.beforeFilter.trim()) {
    add('# Custom rules (before)');
    for (const l of fw.custom.beforeFilter.split('\n')) add(l, custom);
    blank();
  }

  const floating = fw.rules.filter((r) => r.enabled && isFloating(r));
  if (floating.length) {
    add('# Floating rules');
    for (const r of floating) add(ruleText(r, m), { label: `Rule: ${r.description}`, to: '/firewall/rules/floating' });
    blank();
  }
  for (const i of ifaces) {
    const rules = fw.rules.filter((r) => r.enabled && r.interfaces.length === 1 && r.interfaces[0] === i.id);
    if (!rules.length) continue;
    add(`# ${i.name} rules`);
    for (const r of rules) add(ruleText(r, m), { label: `Rule: ${r.description}`, to: `/firewall/rules/${i.id}` });
    blank();
  }

  if (fw.custom.afterFilter.trim()) {
    add('# Custom rules (after)');
    for (const l of fw.custom.afterFilter.split('\n')) add(l, custom);
    blank();
  }
  return L;
}

export const pfConf = (m: Model) => pfRuleset(m).map((l) => l.text).join('\n');

function hostnameIf(i: Iface, m: Model): string {
  const lines: string[] = [header];
  if (i.vlan) lines.push(`vnetid ${i.vlan.tag} parent ${i.vlan.parent}`);
  if (i.role === 'vpn') {
    const wg = m.wireguard;
    lines.push('wgkey <private key stored by OPF>', `wgport ${wg.listenPort}`);
    for (const p of wg.peers) {
      const aips = [p.address, ...p.networks].map((a) => `wgaip ${a}`).join(' ');
      lines.push(`wgpeer ${p.publicKey} ${aips}${p.endpoint ? ` wgendpoint ${p.endpoint.replace(':', ' ')}` : ''}${p.keepalive ? ` wgpka ${p.keepalive}` : ''} wgdescr "${p.name}"`);
    }
  }
  lines.push(`description "${i.name}"`);
  if (i.mtu) lines.push(`mtu ${i.mtu}`);
  if (i.ipv4.mode === 'dhcp') lines.push('inet autoconf');
  if (i.ipv4.mode === 'static' && i.ipv4.address) lines.push(`inet ${i.ipv4.address}/${i.ipv4.prefix}`);
  if (i.ipv6 === 'slaac') lines.push('inet6 autoconf');
  lines.push(i.enabled ? 'up' : 'down');
  // Static routes whose gateway is reached through this interface.
  for (const r of m.routing.routes.filter((x) => x.enabled)) {
    const g = m.routing.gateways.find((x) => x.id === r.gateway);
    if (g?.iface === i.id && g.address !== 'dhcp') lines.push(`!route -q add -net ${r.network} ${g.address}\t# ${r.description}`);
  }
  return lines.join('\n') + '\n';
}

function dhcpdConf(m: Model): string {
  const lines: string[] = [header, '', `option domain-name "${m.system.domain}";`, ''];
  for (const s of m.dhcp) {
    const i = m.interfaces.find((x) => x.id === s.iface);
    if (!s.enabled || !i || i.ipv4.mode !== 'static' || !i.ipv4.address || i.ipv4.prefix === undefined) continue;
    const dns = s.dns === 'self' ? i.ipv4.address : s.dnsServers.join(', ');
    lines.push(`# ${i.name}`);
    lines.push(`subnet ${network(i.ipv4.address, i.ipv4.prefix)} netmask ${netmask(i.ipv4.prefix)} {`);
    lines.push(`\toption routers ${i.ipv4.address};`);
    lines.push(`\toption domain-name-servers ${dns};`);
    lines.push(`\trange ${s.rangeStart} ${s.rangeEnd};`);
    lines.push(`\tdefault-lease-time ${s.leaseHours * 3600};`);
    for (const r of s.reservations) lines.push(`\thost ${r.hostname} {`, `\t\thardware ethernet ${r.mac};`, `\t\tfixed-address ${r.ip};`, '\t}');
    lines.push('}', '');
  }
  return lines.join('\n');
}

function unboundConf(m: Model): string {
  const d = m.dns;
  const inside = staticIfaces(m).filter((i) => i.role !== 'wan');
  const lines: string[] = [header, '', 'server:', '\tinterface: 127.0.0.1'];
  for (const i of inside) lines.push(`\tinterface: ${i.ipv4.address}`);
  lines.push('\taccess-control: 127.0.0.0/8 allow');
  for (const i of inside) lines.push(`\taccess-control: ${network(i.ipv4.address!, i.ipv4.prefix!)}/${i.ipv4.prefix} allow`);
  lines.push('\thide-identity: yes', '\thide-version: yes');
  if (d.dnssec) lines.push('\tauto-trust-anchor-file: "/var/unbound/db/root.key"', '\tval-log-level: 2');
  lines.push(`\tlocal-zone: "${m.system.domain}." static`);
  for (const o of d.overrides) lines.push(`\tlocal-data: "${o.host}.${o.domain}. IN A ${o.ip}"`);
  if (d.registerLeases) for (const s of m.dhcp) for (const r of s.reservations) lines.push(`\tlocal-data: "${r.hostname}.${m.system.domain}. IN A ${r.ip}"`);
  if (d.mode === 'forward') {
    lines.push('', 'forward-zone:', '\tname: "."');
    if (d.forwardTls) lines.push('\tforward-tls-upstream: yes');
    for (const f of d.forwarders) lines.push(`\tforward-addr: ${f}${d.forwardTls ? '@853' : ''}`);
  }
  return lines.join('\n') + '\n';
}

export function generateFiles(m: Model): GeneratedFile[] {
  const files: GeneratedFile[] = [
    { path: '/etc/myname', content: `${m.system.hostname}.${m.system.domain}\n` },
    { path: '/etc/ntpd.conf', content: header + '\n' + m.system.ntpServers.map((s) => `servers ${s}`).join('\n') + '\n' },
    { path: '/etc/pf.conf', content: pfConf(m) },
    { path: '/etc/dhcpd.conf', content: dhcpdConf(m) },
    { path: '/var/unbound/etc/unbound.conf', content: unboundConf(m) },
  ];
  const def = m.routing.gateways.find((g) => g.id === m.routing.defaultGateway);
  if (def && def.address !== 'dhcp') files.push({ path: '/etc/mygate', content: `${def.address}\n` });
  for (const i of m.interfaces) files.push({ path: `/etc/hostname.${i.device}`, content: hostnameIf(i, m) });
  return files;
}
