// Turns the model into the OpenBSD files it replaces. The Go backend
// will own the real generators; these show the user what Apply writes
// and pin down the shape of the output.
import type { Endpoint, Iface, Model, Protocol, Rule } from './types';
import { netmask, network } from '../lib/ip';

export interface GeneratedFile {
  path: string;
  content: string;
}

const header = '# Generated by OPF. Edits here are overwritten; use the web interface.\n';

function ifaceNet(i: Iface): string | null {
  if (i.ipv4.mode !== 'static' || !i.ipv4.address || i.ipv4.prefix === undefined) return null;
  return `${network(i.ipv4.address, i.ipv4.prefix)}/${i.ipv4.prefix}`;
}

function endpoint(e: Endpoint, m: Model): string {
  switch (e.type) {
    case 'any':
      return 'any';
    case 'self':
      return 'self';
    case 'net':
      return `$${e.iface}:network`;
    case 'host':
    case 'network':
      return e.value;
    case 'alias':
      return m.firewall.aliases.some((a) => a.name === e.alias) ? `<${e.alias}>` : e.alias;
  }
}

function proto(p: Protocol): string {
  switch (p) {
    case 'any':
      return '';
    case 'tcp/udp':
      return ' proto { tcp udp }';
    default:
      return ` proto ${p}`;
  }
}

function port(spec: string | undefined, m: Model): string {
  if (!spec) return '';
  if (spec.startsWith('alias:')) {
    const a = m.firewall.aliases.find((x) => x.name === spec.slice(6));
    return a ? ` port { ${a.entries.join(' ')} }` : '';
  }
  return ` port ${spec.replace('-', ':')}`;
}

function rule(r: Rule, m: Model): string {
  const action = r.action === 'reject' ? 'block return' : r.action;
  const log = r.log ? ' log' : '';
  const p = r.protocol === 'tcp' || r.protocol === 'udp' || r.protocol === 'tcp/udp' ? port(r.port, m) : '';
  return `${action} in${log} quick on $${r.iface}${proto(r.protocol)} from ${endpoint(r.source, m)} to ${endpoint(r.destination, m)}${p} label "${r.description.replace(/"/g, "'")}"`;
}

export function pfConf(m: Model): string {
  const ifaces = m.interfaces.filter((i) => i.enabled);
  const wan = ifaces.find((i) => i.role === 'wan');
  const lines: string[] = [header];

  lines.push('# Interfaces');
  for (const i of ifaces) lines.push(`${i.id} = "${i.device}"\t# ${i.name}`);
  lines.push('');

  const tables = m.firewall.aliases.filter((a) => a.type !== 'ports');
  if (tables.length) {
    lines.push('# Aliases');
    for (const a of tables) lines.push(`table <${a.name}> const { ${a.entries.join(' ')} }`);
    lines.push('');
  }
  if (wan?.blockBogons) {
    lines.push('table <bogons> const { 0.0.0.0/8 100.64.0.0/10 127.0.0.0/8 169.254.0.0/16 192.0.0.0/24 198.18.0.0/15 224.0.0.0/3 }');
  }
  if (wan?.blockPrivate) {
    lines.push('table <private> const { 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16 }');
  }
  if (wan?.blockBogons || wan?.blockPrivate) lines.push('');

  lines.push('set skip on lo', 'set block-policy drop', 'set loginterface $' + (wan?.id ?? 'lan'), '');

  if (wan) {
    lines.push('# Outbound NAT');
    lines.push(`match out on $${wan.id} inet from !($${wan.id}:network) to any nat-to ($${wan.id}:0)`, '');
  }

  lines.push('# Defaults: block incoming, allow this firewall to reach out');
  lines.push('block log all', 'pass out quick inet', 'pass out quick inet6', '');

  const lan = ifaces.find((i) => i.role === 'lan');
  if (lan) {
    lines.push('# Anti-lockout: always allow the web interface from LAN');
    lines.push(`pass in quick on $${lan.id} proto tcp to ($${lan.id}) port { 443 22 }`, '');
  }

  if (wan?.blockPrivate) lines.push(`block in log quick on $${wan.id} from <private> label "Block private networks"`);
  if (wan?.blockBogons) lines.push(`block in log quick on $${wan.id} from <bogons> label "Block bogon networks"`);
  if (wan?.blockBogons || wan?.blockPrivate) lines.push('');

  const forwards = m.firewall.forwards.filter((f) => f.enabled && ifaces.some((i) => i.id === f.iface));
  if (forwards.length) {
    lines.push('# Port forwards');
    for (const f of forwards) {
      lines.push(
        `pass in quick on $${f.iface}${proto(f.protocol)} to ($${f.iface}) port ${f.externalPort} rdr-to ${f.target} port ${f.targetPort} label "${f.description}"`,
      );
    }
    lines.push('');
  }

  for (const i of ifaces) {
    const rules = m.firewall.rules.filter((r) => r.iface === i.id && r.enabled);
    if (!rules.length) continue;
    lines.push(`# ${i.name} rules`);
    for (const r of rules) lines.push(rule(r, m));
    lines.push('');
  }
  return lines.join('\n');
}

function hostnameIf(i: Iface, m: Model): string {
  const lines: string[] = [header.trimEnd()];
  if (i.vlan) lines.push(`vnetid ${i.vlan.tag} parent ${i.vlan.parent}`);
  if (i.role === 'vpn') {
    const wg = m.wireguard;
    lines.push('wgkey <private key stored by OPF>', `wgport ${wg.listenPort}`);
    for (const p of wg.peers) {
      lines.push(`wgpeer ${p.publicKey} wgaip ${p.address}${p.endpoint ? ` wgendpoint ${p.endpoint.replace(':', ' ')}` : ''}${p.keepalive ? ` wgpka ${p.keepalive}` : ''} wgdescr "${p.name}"`);
    }
  }
  lines.push(`description "${i.name}"`);
  if (i.mtu) lines.push(`mtu ${i.mtu}`);
  if (i.ipv4.mode === 'dhcp') lines.push('inet autoconf');
  if (i.ipv4.mode === 'static' && i.ipv4.address) lines.push(`inet ${i.ipv4.address}/${i.ipv4.prefix}`);
  if (i.ipv6 === 'slaac') lines.push('inet6 autoconf');
  lines.push(i.enabled ? 'up' : 'down');
  return lines.join('\n') + '\n';
}

function dhcpdConf(m: Model): string {
  const lines: string[] = [header, `option domain-name "${m.system.domain}";`, ''];
  for (const s of m.dhcp) {
    const i = m.interfaces.find((x) => x.id === s.iface);
    if (!s.enabled || !i || i.ipv4.mode !== 'static' || !i.ipv4.address || i.ipv4.prefix === undefined) continue;
    const dns = s.dns === 'self' ? i.ipv4.address : s.dnsServers.join(', ');
    lines.push(`# ${i.name}`);
    lines.push(`subnet ${network(i.ipv4.address, i.ipv4.prefix)} netmask ${netmask(i.ipv4.prefix)} {`);
    lines.push(`\toption routers ${i.ipv4.address};`);
    lines.push(`\toption domain-name-servers ${dns};`);
    lines.push(`\trange ${s.rangeStart} ${s.rangeEnd};`);
    lines.push(`\tdefault-lease-time ${s.leaseHours * 3600};`);
    for (const r of s.reservations) {
      lines.push(`\thost ${r.hostname} {`, `\t\thardware ethernet ${r.mac};`, `\t\tfixed-address ${r.ip};`, '\t}');
    }
    lines.push('}', '');
  }
  return lines.join('\n');
}

function unboundConf(m: Model): string {
  const d = m.dns;
  const inside = m.interfaces.filter((i) => i.enabled && i.role !== 'wan' && i.ipv4.mode === 'static');
  const lines: string[] = [header, 'server:', '\tinterface: 127.0.0.1'];
  for (const i of inside) lines.push(`\tinterface: ${i.ipv4.address}`);
  lines.push('\taccess-control: 127.0.0.0/8 allow');
  for (const i of inside) {
    const net = ifaceNet(i);
    if (net) lines.push(`\taccess-control: ${net} allow`);
  }
  lines.push('\thide-identity: yes', '\thide-version: yes');
  if (d.dnssec) lines.push('\tauto-trust-anchor-file: "/var/unbound/db/root.key"', '\tval-log-level: 2');
  lines.push(`\tlocal-zone: "${m.system.domain}." static`);
  for (const o of d.overrides) lines.push(`\tlocal-data: "${o.host}.${o.domain}. IN A ${o.ip}"`);
  if (d.registerLeases) {
    for (const s of m.dhcp) for (const r of s.reservations) lines.push(`\tlocal-data: "${r.hostname}.${m.system.domain}. IN A ${r.ip}"`);
  }
  if (d.mode === 'forward') {
    lines.push('', 'forward-zone:', '\tname: "."');
    if (d.forwardTls) lines.push('\tforward-tls-upstream: yes');
    for (const f of d.forwarders) lines.push(`\tforward-addr: ${f}${d.forwardTls ? '@853' : ''}`);
  }
  return lines.join('\n') + '\n';
}

export function generateFiles(m: Model): GeneratedFile[] {
  const files: GeneratedFile[] = [
    { path: '/etc/myname', content: `${m.system.hostname}.${m.system.domain}\n` },
    { path: '/etc/ntpd.conf', content: header + m.system.ntpServers.map((s) => `servers ${s}`).join('\n') + '\n' },
    { path: '/etc/pf.conf', content: pfConf(m) },
    { path: '/etc/dhcpd.conf', content: dhcpdConf(m) },
    { path: '/var/unbound/etc/unbound.conf', content: unboundConf(m) },
  ];
  for (const i of m.interfaces) files.push({ path: `/etc/hostname.${i.device}`, content: hostnameIf(i, m) });
  return files;
}
