package pf

import (
	"fmt"
	"net"
	"strings"
)

const header = "# Generated by OPF. Edits here are overwritten; use the web interface."

// GatewayStatus holds runtime gateway information for DHCP gateways.
type GatewayStatus struct {
	Address string `json:"address"`
}

// GatewayStatuses maps gateway IDs to their current status.
var GatewayStatuses = map[string]GatewayStatus{}

// GenerateRule converts a single rule to pf.conf syntax.
func GenerateRule(r *Rule, m *Model) string {
	if r.IsRaw() {
		return strings.TrimSpace(r.Text)
	}
	return generateFormRule(r, m)
}

func generateFormRule(r *Rule, m *Model) string {
	var out []string

	// Action
	switch r.Action {
	case ActionReject:
		out = append(out, "block return")
	case ActionBlock:
		action := "block"
		switch r.BlockReturn {
		case BlockReturnRST:
			action = "block return-rst"
			if r.ReturnRstTTL != nil {
				action += fmt.Sprintf(" ttl %d", *r.ReturnRstTTL)
			}
		case BlockReturnICMP:
			action = "block return-icmp"
			if r.ReturnICMPCode != "" {
				action += fmt.Sprintf(" (%s)", r.ReturnICMPCode)
			}
		case BlockReturnICMP6:
			action = "block return-icmp6"
			if r.ReturnICMPCode != "" {
				action += fmt.Sprintf(" (%s)", r.ReturnICMPCode)
			}
		case BlockReturnReturn:
			action = "block return"
		}
		out = append(out, action)
	default:
		out = append(out, string(r.Action))
	}

	// Direction
	if r.Direction != DirectionAny {
		out = append(out, string(r.Direction))
	}

	// Log
	if r.Log == LogOn {
		out = append(out, "log")
	} else if r.Log == LogAll {
		out = append(out, "log (all)")
	}

	// Quick
	if r.Quick {
		out = append(out, "quick")
	}

	// Join what we have so far
	s := strings.Join(out, " ")

	// On clause
	s += onClause(r.Interfaces)

	// Address family
	if r.Family != FamilyAny && r.Family != "" {
		s += " " + string(r.Family)
	}

	// Protocol
	s += proto(r.Protocol)

	// Source and destination
	hasPorts := r.Protocol == ProtoTCP || r.Protocol == ProtoUDP || r.Protocol == ProtoTCPUDP
	sp := ""
	dp := ""
	if hasPorts {
		sp = portExpr(r.SourcePort, m)
		dp = portExpr(r.Port, m)
	}

	if r.Source.Type == EndpointAny && r.Destination.Type == EndpointAny && sp == "" && dp == "" && r.OSFingerprint == "" {
		s += " all"
	} else {
		s += " from " + endpoint(r.Source, m) + sp
		if r.OSFingerprint != "" {
			s += " os " + quote(r.OSFingerprint)
		}
		s += " to " + endpoint(r.Destination, m) + dp
	}

	// TCP flags
	if (r.Protocol == ProtoTCP || r.Protocol == ProtoTCPUDP) && r.TCPFlags != "" && r.TCPFlags != "S/SA" {
		s += " flags " + r.TCPFlags
	}

	// ICMP type
	if (r.Protocol == ProtoICMP || r.Protocol == ProtoICMP6) && r.ICMPType != "" {
		if r.Protocol == ProtoICMP6 {
			s += " icmp6-type " + r.ICMPType
		} else {
			s += " icmp-type " + r.ICMPType
		}
	}

	// Tagged
	if r.Tagged != "" {
		s += " tagged " + r.Tagged
	}

	// Tag
	if r.Tag != "" {
		s += " tag " + r.Tag
	}

	// Probability
	if r.Probability != nil && *r.Probability < 100 {
		s += fmt.Sprintf(" probability %d%%", *r.Probability)
	}

	// Once
	if r.Once {
		s += " once"
	}

	// State options (only for pass rules)
	if r.State != nil && r.Action == ActionPass {
		st := r.State
		if st.Mode == StateModeNone {
			s += " no state"
		} else {
			var opts []string
			if st.MaxStates != nil {
				opts = append(opts, fmt.Sprintf("max %d", *st.MaxStates))
			}
			if st.MaxSrcConn != nil {
				opts = append(opts, fmt.Sprintf("max-src-conn %d", *st.MaxSrcConn))
			}
			if st.MaxSrcConnRate != nil {
				opts = append(opts, fmt.Sprintf("max-src-conn-rate %d/%d", st.MaxSrcConnRate.Count, st.MaxSrcConnRate.Seconds))
			}
			if st.Overload != "" {
				overloadOpt := fmt.Sprintf("overload <%s>", st.Overload)
				if st.FlushGlobal {
					overloadOpt += " flush global"
				}
				opts = append(opts, overloadOpt)
			}
			if st.Sloppy {
				opts = append(opts, "sloppy")
			}
			if st.Policy != "" {
				opts = append(opts, string(st.Policy))
			}

			var kw string
			switch st.Mode {
			case StateModeModulate:
				kw = "modulate state"
			case StateModeSynproxy:
				kw = "synproxy state"
			default:
				kw = "keep state"
			}

			if len(opts) > 0 || st.Mode != StateModeKeep {
				s += " " + kw
				if len(opts) > 0 {
					s += " (" + strings.Join(opts, ", ") + ")"
				}
			}
		}
	}

	// Priority
	if r.Prio != nil {
		s += fmt.Sprintf(" set prio %d", *r.Prio)
	}

	// Rtable
	if r.RTable != nil {
		s += fmt.Sprintf(" rtable %d", *r.RTable)
	}

	// Route-to
	if r.Gateway != "" {
		if addr := gatewayAddr(r.Gateway, m); addr != "" {
			s += " route-to " + addr
		}
	}

	// Reply-to
	if r.ReplyTo != "" {
		if addr := gatewayAddr(r.ReplyTo, m); addr != "" {
			s += " reply-to " + addr
		}
	}

	// Label (description)
	if r.Description != "" {
		s += " label " + quote(r.Description)
	}

	return s
}

func endpoint(e Endpoint, m *Model) string {
	not := ""
	if e.Not {
		not = "! "
	}

	switch e.Type {
	case EndpointAny:
		return "any"
	case EndpointSelf:
		return not + "self"
	case EndpointNet:
		return fmt.Sprintf("%s$%s:network", not, e.Iface)
	case EndpointIfaddr:
		return fmt.Sprintf("%s($%s)", not, e.Iface)
	case EndpointHost, EndpointNetwork:
		return not + e.Value
	case EndpointAlias:
		// Check if it's a non-port alias
		if m != nil {
			for _, a := range m.Firewall.Aliases {
				if a.Name == e.Alias && a.Type != AliasPorts {
					return fmt.Sprintf("%s<%s>", not, e.Alias)
				}
			}
		}
		return not + e.Alias
	default:
		return "any"
	}
}

func proto(p Protocol) string {
	switch p {
	case ProtoAny, "":
		return ""
	case ProtoTCPUDP:
		return " proto { tcp udp }"
	default:
		return " proto " + string(p)
	}
}

func portExpr(spec string, m *Model) string {
	s := strings.TrimSpace(spec)
	if s == "" {
		return ""
	}

	// Alias reference
	if strings.HasPrefix(s, "alias:") {
		aliasName := s[6:]
		if m != nil {
			for _, a := range m.Firewall.Aliases {
				if a.Name == aliasName {
					return " port { " + strings.Join(a.Entries, " ") + " }"
				}
			}
		}
		return ""
	}

	// Comma-separated list
	if strings.Contains(s, ",") {
		ports := strings.Split(s, ",")
		var trimmed []string
		for _, p := range ports {
			if t := strings.TrimSpace(p); t != "" {
				trimmed = append(trimmed, t)
			}
		}
		return " port { " + strings.Join(trimmed, " ") + " }"
	}

	// Convert dash range to colon
	s = strings.Replace(s, "-", ":", 1)
	// Only convert if it's a simple range like 8000-8080, not operators
	if matched := strings.Contains(spec, "-"); matched {
		parts := strings.Split(spec, "-")
		if len(parts) == 2 && isNumber(parts[0]) && isNumber(parts[1]) {
			s = parts[0] + ":" + parts[1]
		}
	}

	return " port " + s
}

func gatewayAddr(id string, m *Model) string {
	if m == nil {
		return ""
	}
	for _, g := range m.Routing.Gateways {
		if g.ID == id {
			if g.Address == "dhcp" {
				if status, ok := GatewayStatuses[g.ID]; ok {
					return status.Address
				}
				return "0.0.0.0"
			}
			return g.Address
		}
	}
	return ""
}

func onClause(ifaces []string) string {
	if len(ifaces) == 0 {
		return ""
	}
	if len(ifaces) == 1 {
		return " on $" + ifaces[0]
	}
	var parts []string
	for _, i := range ifaces {
		parts = append(parts, "$"+i)
	}
	return " on { " + strings.Join(parts, " ") + " }"
}

func quote(s string) string {
	// Replace double quotes with single quotes to avoid escaping
	escaped := strings.ReplaceAll(s, "\"", "'")
	return fmt.Sprintf("%q", escaped)
}

// GenerateNATRule converts a NAT rule to pf.conf syntax.
func GenerateNATRule(n *NATRule, m *Model) string {
	hosts := fmt.Sprintf("on $%s inet from %s to %s",
		n.Iface, endpoint(n.Source, m), endpoint(n.Destination, m))

	// Exception rules need to stop evaluation before any nat-to applies
	if n.Translation.Type == TranslationNone {
		return fmt.Sprintf("pass out quick %s label %s", hosts, quote(n.Description))
	}

	s := "match out " + hosts
	if n.Translation.Type == TranslationIfaddr {
		s += fmt.Sprintf(" nat-to ($%s:0)", n.Iface)
	} else {
		s += " nat-to " + n.Translation.Value
	}

	if n.Pool != "" {
		s += " " + string(n.Pool)
	}
	if n.StaticPort {
		s += " static-port"
	}

	return s + " label " + quote(n.Description)
}

// AutomaticNAT generates NAT rules for internal networks to WANs.
func AutomaticNAT(m *Model) []NATRule {
	wans := []Iface{}
	for _, i := range m.Interfaces {
		if i.Enabled && i.Role == RoleWAN {
			wans = append(wans, i)
		}
	}

	statics := staticIfaces(m)
	var rules []NATRule

	for _, w := range wans {
		for _, i := range statics {
			if i.Role == RoleWAN {
				continue
			}
			rules = append(rules, NATRule{
				ID:          fmt.Sprintf("auto-%s-%s", w.ID, i.ID),
				Enabled:     true,
				Iface:       w.ID,
				Source:      Endpoint{Type: EndpointNet, Iface: i.ID},
				Destination: Endpoint{Type: EndpointAny},
				Translation: Translation{Type: TranslationIfaddr},
				StaticPort:  false,
				Description: fmt.Sprintf("Automatic: %s to %s", i.Name, w.Name),
			})
		}
	}

	return rules
}

// GeneratePortForward converts a port forward to pf.conf rules.
func GeneratePortForward(f *PortForward, m *Model) []string {
	log := ""
	if f.Log {
		log = " log"
	}
	from := endpoint(f.Source, m)

	lines := []string{
		fmt.Sprintf("pass in%s quick on $%s%s from %s to ($%s) port %s rdr-to %s port %s label %s",
			log, f.Iface, proto(f.Protocol), from, f.Iface, f.ExternalPort, f.Target, f.TargetPort, quote(f.Description)),
	}

	if f.Reflection {
		inside := staticIfaces(m)
		for _, i := range inside {
			if i.Role != RoleLAN && i.Role != RoleOPT {
				continue
			}
			lines = append(lines,
				fmt.Sprintf("pass in quick on $%s%s from $%s:network to ($%s) port %s rdr-to %s port %s",
					i.ID, proto(f.Protocol), i.ID, f.Iface, f.ExternalPort, f.Target, f.TargetPort),
				fmt.Sprintf("match out on $%s%s from $%s:network to %s port %s nat-to ($%s)",
					i.ID, proto(f.Protocol), i.ID, f.Target, f.TargetPort, i.ID),
			)
		}
	}

	return lines
}

func staticIfaces(m *Model) []Iface {
	var result []Iface
	for _, i := range m.Interfaces {
		if i.Enabled && i.IPv4.Mode == IPv4Static && i.IPv4.Address != "" && i.IPv4.Prefix != nil {
			result = append(result, i)
		}
	}
	return result
}

// isFloating returns true if the rule applies to multiple or no interfaces.
func isFloating(r *Rule) bool {
	return len(r.Interfaces) != 1
}

// GeneratePfRuleset generates the full pf.conf as a list of lines with origins.
func GeneratePfRuleset(m *Model) []PfLine {
	var lines []PfLine
	add := func(text string, origin *Origin) {
		lines = append(lines, PfLine{Text: text, Origin: origin})
	}
	blank := func() {
		lines = append(lines, PfLine{Text: ""})
	}

	fw := m.Firewall
	o := fw.Options
	ifaces := []Iface{}
	for _, i := range m.Interfaces {
		if i.Enabled {
			ifaces = append(ifaces, i)
		}
	}

	var wan, lan *Iface
	for i := range ifaces {
		if ifaces[i].Role == RoleWAN && wan == nil {
			wan = &ifaces[i]
		}
		if ifaces[i].Role == RoleLAN && lan == nil {
			lan = &ifaces[i]
		}
	}

	settings := &Origin{Label: "Firewall settings", To: "/firewall/settings"}
	custom := &Origin{Label: "Custom pf", To: "/firewall/ruleset"}

	add(header, nil)
	blank()

	// Interfaces
	add("# Interfaces", nil)
	for _, i := range ifaces {
		add(fmt.Sprintf("%s = \"%s\"", i.ID, i.Device), &Origin{Label: fmt.Sprintf("Interface %s", i.Name), To: fmt.Sprintf("/interfaces/%s", i.ID)})
	}
	blank()

	// Aliases
	add("# Aliases", nil)
	for _, a := range fw.Aliases {
		if a.Type == AliasPorts {
			continue
		}
		origin := &Origin{Label: fmt.Sprintf("Alias %s", a.Name), To: "/firewall/aliases"}
		switch a.Type {
		case AliasTable:
			add(fmt.Sprintf("table <%s> persist", a.Name), origin)
		case AliasURL:
			refreshHours := 24
			if a.RefreshHours != nil {
				refreshHours = *a.RefreshHours
			}
			add(fmt.Sprintf("table <%s> persist file \"/var/opf/tables/%s\"\t# refreshed every %dh from %s", a.Name, a.Name, refreshHours, a.URL), origin)
		default:
			add(fmt.Sprintf("table <%s> const { %s }", a.Name, strings.Join(a.Entries, " ")), origin)
		}
	}
	if wan != nil && wan.BlockBogons {
		add("table <bogons> const { 0.0.0.0/8 100.64.0.0/10 127.0.0.0/8 169.254.0.0/16 192.0.0.0/24 198.18.0.0/15 224.0.0.0/3 }", &Origin{Label: "WAN protection", To: fmt.Sprintf("/interfaces/%s", wan.ID)})
	}
	if wan != nil && wan.BlockPrivate {
		add("table <private> const { 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16 }", &Origin{Label: "WAN protection", To: fmt.Sprintf("/interfaces/%s", wan.ID)})
	}
	blank()

	// Options
	add("# Options", nil)
	add(fmt.Sprintf("set block-policy %s", o.BlockPolicy), settings)
	add(fmt.Sprintf("set state-policy %s", o.StatePolicy), settings)
	add(fmt.Sprintf("set optimization %s", o.Optimization), settings)
	add(fmt.Sprintf("set limit states %d", o.MaxStates), settings)
	syncookies := string(o.Syncookies)
	if o.Syncookies == SyncookiesAdaptive {
		syncookies += " (start 25%, end 12%)"
	}
	add(fmt.Sprintf("set syncookies %s", syncookies), settings)
	add("set skip on lo", settings)
	if wan != nil {
		add(fmt.Sprintf("set loginterface $%s", wan.ID), settings)
	}
	for _, line := range strings.Split(fw.Custom.Options, "\n") {
		if strings.TrimSpace(line) != "" {
			add(line, custom)
		}
	}
	if o.Scrub.Enabled {
		var scrubOpts []string
		if o.Scrub.NoDf {
			scrubOpts = append(scrubOpts, "no-df")
		}
		if o.Scrub.RandomID {
			scrubOpts = append(scrubOpts, "random-id")
		}
		if o.Scrub.MaxMss != nil {
			scrubOpts = append(scrubOpts, fmt.Sprintf("max-mss %d", *o.Scrub.MaxMss))
		}
		add(fmt.Sprintf("match in all scrub (%s)", strings.Join(scrubOpts, " ")), settings)
	}
	blank()

	// Outbound NAT
	add("# Outbound NAT", nil)
	natOrigin := &Origin{Label: "Outbound NAT", To: "/firewall/nat/outbound"}

	var manual, auto []NATRule
	if fw.OutboundNAT.Mode != NATModeAuto {
		for _, r := range fw.OutboundNAT.Rules {
			if r.Enabled {
				manual = append(manual, r)
			}
		}
	}
	if fw.OutboundNAT.Mode != NATModeManual {
		auto = AutomaticNAT(m)
	}

	// Exceptions first (they have pass out quick)
	for _, n := range manual {
		if n.Translation.Type == TranslationNone {
			add(GenerateNATRule(&n, m), natOrigin)
		}
	}
	// Automatic NAT
	for i := range auto {
		add(GenerateNATRule(&auto[i], m), natOrigin)
	}
	// Manual NAT (non-exceptions)
	for _, n := range manual {
		if n.Translation.Type != TranslationNone {
			add(GenerateNATRule(&n, m), natOrigin)
		}
	}
	blank()

	// Defaults
	add("# Defaults", nil)
	if o.LogDefaultBlock {
		add("block log all", &Origin{Label: "Default block", To: "/firewall/settings"})
	} else {
		add("block all", &Origin{Label: "Default block", To: "/firewall/settings"})
	}
	add("pass out quick inet", &Origin{Label: "This firewall's own traffic", To: "/firewall/settings"})
	add("pass out quick inet6", &Origin{Label: "This firewall's own traffic", To: "/firewall/settings"})
	if lan != nil {
		add(fmt.Sprintf("pass in quick on $%s proto tcp to ($%s) port { 443 22 } label \"Anti-lockout\"", lan.ID, lan.ID), &Origin{Label: "Anti-lockout", To: fmt.Sprintf("/interfaces/%s", lan.ID)})
	}
	if wan != nil && wan.BlockPrivate {
		add(fmt.Sprintf("block in log quick on $%s from <private> label \"Block private networks\"", wan.ID), &Origin{Label: "WAN protection", To: fmt.Sprintf("/interfaces/%s", wan.ID)})
	}
	if wan != nil && wan.BlockBogons {
		add(fmt.Sprintf("block in log quick on $%s from <bogons> label \"Block bogon networks\"", wan.ID), &Origin{Label: "WAN protection", To: fmt.Sprintf("/interfaces/%s", wan.ID)})
	}
	blank()

	// Port forwards
	var forwards []PortForward
	for _, f := range fw.Forwards {
		if !f.Enabled {
			continue
		}
		// Check if interface exists
		for _, i := range ifaces {
			if i.ID == f.Iface {
				forwards = append(forwards, f)
				break
			}
		}
	}
	if len(forwards) > 0 {
		add("# Port forwards", nil)
		for i := range forwards {
			for _, line := range GeneratePortForward(&forwards[i], m) {
				add(line, &Origin{Label: fmt.Sprintf("Port forward: %s", forwards[i].Description), To: "/firewall/nat"})
			}
		}
		blank()
	}

	// Custom before filter
	if strings.TrimSpace(fw.Custom.BeforeFilter) != "" {
		add("# Custom rules (before)", nil)
		for _, line := range strings.Split(fw.Custom.BeforeFilter, "\n") {
			add(line, custom)
		}
		blank()
	}

	// Floating rules
	var floating []Rule
	for i := range fw.Rules {
		if fw.Rules[i].Enabled && isFloating(&fw.Rules[i]) {
			floating = append(floating, fw.Rules[i])
		}
	}
	if len(floating) > 0 {
		add("# Floating rules", nil)
		for i := range floating {
			add(GenerateRule(&floating[i], m), &Origin{Label: fmt.Sprintf("Rule: %s", floating[i].Description), To: "/firewall/rules/floating"})
		}
		blank()
	}

	// Per-interface rules
	for _, iface := range ifaces {
		var ifaceRules []Rule
		for i := range fw.Rules {
			r := &fw.Rules[i]
			if r.Enabled && len(r.Interfaces) == 1 && r.Interfaces[0] == iface.ID {
				ifaceRules = append(ifaceRules, *r)
			}
		}
		if len(ifaceRules) == 0 {
			continue
		}
		add(fmt.Sprintf("# %s rules", iface.Name), nil)
		for i := range ifaceRules {
			add(GenerateRule(&ifaceRules[i], m), &Origin{Label: fmt.Sprintf("Rule: %s", ifaceRules[i].Description), To: fmt.Sprintf("/firewall/rules/%s", iface.ID)})
		}
		blank()
	}

	// Custom after filter
	if strings.TrimSpace(fw.Custom.AfterFilter) != "" {
		add("# Custom rules (after)", nil)
		for _, line := range strings.Split(fw.Custom.AfterFilter, "\n") {
			add(line, custom)
		}
		blank()
	}

	return lines
}

// GeneratePfConf generates the full pf.conf as a string.
func GeneratePfConf(m *Model) string {
	lines := GeneratePfRuleset(m)
	var parts []string
	for _, l := range lines {
		parts = append(parts, l.Text)
	}
	return strings.Join(parts, "\n")
}

// GenerateHostnameIf generates /etc/hostname.<device> content.
func GenerateHostnameIf(i *Iface, m *Model) string {
	var lines []string
	lines = append(lines, header)

	if i.VLAN != nil {
		lines = append(lines, fmt.Sprintf("vnetid %d parent %s", i.VLAN.Tag, i.VLAN.Parent))
	}

	if i.Role == RoleVPN {
		wg := m.WireGuard
		lines = append(lines, "wgkey <private key stored by OPF>", fmt.Sprintf("wgport %d", wg.ListenPort))
		for _, p := range wg.Peers {
			aips := []string{fmt.Sprintf("wgaip %s", p.Address)}
			for _, net := range p.Networks {
				aips = append(aips, fmt.Sprintf("wgaip %s", net))
			}
			line := fmt.Sprintf("wgpeer %s %s", p.PublicKey, strings.Join(aips, " "))
			if p.Endpoint != "" {
				// Convert host:port to "host port"
				parts := strings.SplitN(p.Endpoint, ":", 2)
				if len(parts) == 2 {
					line += fmt.Sprintf(" wgendpoint %s %s", parts[0], parts[1])
				}
			}
			if p.Keepalive != nil {
				line += fmt.Sprintf(" wgpka %d", *p.Keepalive)
			}
			line += fmt.Sprintf(" wgdescr \"%s\"", p.Name)
			lines = append(lines, line)
		}
	}

	lines = append(lines, fmt.Sprintf("description \"%s\"", i.Name))

	if i.MTU != nil {
		lines = append(lines, fmt.Sprintf("mtu %d", *i.MTU))
	}

	if i.IPv4.Mode == IPv4DHCP {
		lines = append(lines, "inet autoconf")
	}
	if i.IPv4.Mode == IPv4Static && i.IPv4.Address != "" {
		lines = append(lines, fmt.Sprintf("inet %s/%d", i.IPv4.Address, *i.IPv4.Prefix))
	}
	if i.IPv6 == IPv6SLAAC {
		lines = append(lines, "inet6 autoconf")
	}

	if i.Enabled {
		lines = append(lines, "up")
	} else {
		lines = append(lines, "down")
	}

	// Static routes through this interface
	for _, r := range m.Routing.Routes {
		if !r.Enabled {
			continue
		}
		for _, g := range m.Routing.Gateways {
			if g.ID == r.Gateway && g.Iface == i.ID && g.Address != "dhcp" {
				lines = append(lines, fmt.Sprintf("!route -q add -net %s %s\t# %s", r.Network, g.Address, r.Description))
				break
			}
		}
	}

	return strings.Join(lines, "\n") + "\n"
}

// GenerateDHCPdConf generates /etc/dhcpd.conf content.
func GenerateDHCPdConf(m *Model) string {
	var lines []string
	lines = append(lines, header, "", fmt.Sprintf("option domain-name \"%s\";", m.System.Domain), "")

	for _, s := range m.DHCP {
		if !s.Enabled {
			continue
		}
		var iface *Iface
		for i := range m.Interfaces {
			if m.Interfaces[i].ID == s.Iface {
				iface = &m.Interfaces[i]
				break
			}
		}
		if iface == nil || iface.IPv4.Mode != IPv4Static || iface.IPv4.Address == "" || iface.IPv4.Prefix == nil {
			continue
		}

		dns := iface.IPv4.Address
		if s.DNS == DNSModeCustom {
			dns = strings.Join(s.DNSServers, ", ")
		}

		lines = append(lines, fmt.Sprintf("# %s", iface.Name))
		lines = append(lines, fmt.Sprintf("subnet %s netmask %s {", networkAddr(iface.IPv4.Address, *iface.IPv4.Prefix), netmask(*iface.IPv4.Prefix)))
		lines = append(lines, fmt.Sprintf("\toption routers %s;", iface.IPv4.Address))
		lines = append(lines, fmt.Sprintf("\toption domain-name-servers %s;", dns))
		lines = append(lines, fmt.Sprintf("\trange %s %s;", s.RangeStart, s.RangeEnd))
		lines = append(lines, fmt.Sprintf("\tdefault-lease-time %d;", s.LeaseHours*3600))

		for _, r := range s.Reservations {
			lines = append(lines, fmt.Sprintf("\thost %s {", r.Hostname))
			lines = append(lines, fmt.Sprintf("\t\thardware ethernet %s;", r.MAC))
			lines = append(lines, fmt.Sprintf("\t\tfixed-address %s;", r.IP))
			lines = append(lines, "\t}")
		}

		lines = append(lines, "}", "")
	}

	return strings.Join(lines, "\n")
}

// GenerateUnboundConf generates /var/unbound/etc/unbound.conf content.
func GenerateUnboundConf(m *Model) string {
	d := m.DNS
	inside := staticIfaces(m)
	insideNonWAN := []Iface{}
	for _, i := range inside {
		if i.Role != RoleWAN {
			insideNonWAN = append(insideNonWAN, i)
		}
	}

	var lines []string
	lines = append(lines, header, "", "server:", "\tinterface: 127.0.0.1")

	for _, i := range insideNonWAN {
		lines = append(lines, fmt.Sprintf("\tinterface: %s", i.IPv4.Address))
	}

	lines = append(lines, "\taccess-control: 127.0.0.0/8 allow")
	for _, i := range insideNonWAN {
		lines = append(lines, fmt.Sprintf("\taccess-control: %s/%d allow", networkAddr(i.IPv4.Address, *i.IPv4.Prefix), *i.IPv4.Prefix))
	}

	lines = append(lines, "\thide-identity: yes", "\thide-version: yes")

	if d.DNSSEC {
		lines = append(lines, "\tauto-trust-anchor-file: \"/var/unbound/db/root.key\"", "\tval-log-level: 2")
	}

	lines = append(lines, fmt.Sprintf("\tlocal-zone: \"%s.\" static", m.System.Domain))

	for _, o := range d.Overrides {
		lines = append(lines, fmt.Sprintf("\tlocal-data: \"%s.%s. IN A %s\"", o.Host, o.Domain, o.IP))
	}

	if d.RegisterLeases {
		for _, s := range m.DHCP {
			for _, r := range s.Reservations {
				lines = append(lines, fmt.Sprintf("\tlocal-data: \"%s.%s. IN A %s\"", r.Hostname, m.System.Domain, r.IP))
			}
		}
	}

	if d.Mode == ResolverModeForward {
		lines = append(lines, "", "forward-zone:", "\tname: \".\"")
		if d.ForwardTLS {
			lines = append(lines, "\tforward-tls-upstream: yes")
		}
		for _, f := range d.Forwarders {
			if d.ForwardTLS {
				lines = append(lines, fmt.Sprintf("\tforward-addr: %s@853", f))
			} else {
				lines = append(lines, fmt.Sprintf("\tforward-addr: %s", f))
			}
		}
	}

	return strings.Join(lines, "\n") + "\n"
}

// GenerateFiles generates all config files from the model.
func GenerateFiles(m *Model) []GeneratedFile {
	files := []GeneratedFile{
		{Path: "/etc/myname", Content: fmt.Sprintf("%s.%s\n", m.System.Hostname, m.System.Domain)},
		{Path: "/etc/ntpd.conf", Content: header + "\n" + ntpdConf(m.System.NTPServers)},
		{Path: "/etc/pf.conf", Content: GeneratePfConf(m)},
		{Path: "/etc/dhcpd.conf", Content: GenerateDHCPdConf(m)},
		{Path: "/var/unbound/etc/unbound.conf", Content: GenerateUnboundConf(m)},
	}

	// Default gateway
	for _, g := range m.Routing.Gateways {
		if g.ID == m.Routing.DefaultGateway && g.Address != "dhcp" {
			files = append(files, GeneratedFile{Path: "/etc/mygate", Content: g.Address + "\n"})
			break
		}
	}

	// Interface files
	for i := range m.Interfaces {
		files = append(files, GeneratedFile{
			Path:    fmt.Sprintf("/etc/hostname.%s", m.Interfaces[i].Device),
			Content: GenerateHostnameIf(&m.Interfaces[i], m),
		})
	}

	return files
}

func ntpdConf(servers []string) string {
	var lines []string
	for _, s := range servers {
		lines = append(lines, fmt.Sprintf("servers %s", s))
	}
	return strings.Join(lines, "\n") + "\n"
}

func networkAddr(address string, prefix int) string {
	ip := net.ParseIP(address)
	if ip == nil {
		return address
	}
	mask := net.CIDRMask(prefix, 32)
	return ip.Mask(mask).String()
}

func netmask(prefix int) string {
	mask := net.CIDRMask(prefix, 32)
	return net.IP(mask).String()
}
