package pf

import (
	"fmt"
	"net"
	"regexp"
	"strings"
	"unicode"
)

const header = "# Generated by OPF. Edits here are overwritten; use the web interface."

// GatewayStatus holds runtime gateway information for DHCP gateways.
type GatewayStatus struct {
	Address string `json:"address"`
}

// GatewayStatuses maps gateway IDs to their current status.
var GatewayStatuses = map[string]GatewayStatus{}

// GenerateRule converts a single rule to pf.conf syntax.
func GenerateRule(r *Rule, m *Model) string {
	if r.IsRaw() {
		return strings.TrimSpace(r.Text)
	}
	return generateFormRule(r, m)
}

func generateFormRule(r *Rule, m *Model) string {
	var out []string

	// Action
	switch r.Action {
	case ActionReject:
		out = append(out, "block return")
	case ActionBlock:
		action := "block"
		switch r.BlockReturn {
		case BlockReturnRST:
			action = "block return-rst"
			if r.ReturnRstTTL != nil {
				action += fmt.Sprintf(" ttl %d", *r.ReturnRstTTL)
			}
		case BlockReturnICMP:
			action = "block return-icmp"
			if r.ReturnICMPCode != "" {
				action += fmt.Sprintf(" (%s)", r.ReturnICMPCode)
			}
		case BlockReturnICMP6:
			action = "block return-icmp6"
			if r.ReturnICMPCode != "" {
				action += fmt.Sprintf(" (%s)", r.ReturnICMPCode)
			}
		case BlockReturnReturn:
			action = "block return"
		}
		out = append(out, action)
	default:
		out = append(out, string(r.Action))
	}

	// Direction
	if r.Direction != DirectionAny {
		out = append(out, string(r.Direction))
	}

	// Log
	if r.Log == LogOn {
		out = append(out, "log")
	} else if r.Log == LogAll {
		out = append(out, "log (all)")
	}

	// Quick
	if r.Quick {
		out = append(out, "quick")
	}

	// Join what we have so far
	s := strings.Join(out, " ")

	// On clause
	s += onClause(r.Interfaces, r.Groups)

	// Address family
	if r.Family != FamilyAny && r.Family != "" {
		s += " " + string(r.Family)
	}

	// Protocol
	s += proto(r.Protocol)

	// Source and destination
	hasPorts := r.Protocol == ProtoTCP || r.Protocol == ProtoUDP || r.Protocol == ProtoTCPUDP
	sp := ""
	dp := ""
	if hasPorts {
		sp = portExpr(r.SourcePort, m)
		dp = portExpr(r.Port, m)
	}

	if r.Source.Type == EndpointAny && r.Destination.Type == EndpointAny && sp == "" && dp == "" && r.OSFingerprint == "" {
		s += " all"
	} else {
		s += " from " + endpoint(r.Source, m) + sp
		if r.OSFingerprint != "" {
			s += " os " + quote(r.OSFingerprint)
		}
		s += " to " + endpoint(r.Destination, m) + dp
	}

	// TCP flags
	if (r.Protocol == ProtoTCP || r.Protocol == ProtoTCPUDP) && r.TCPFlags != "" && r.TCPFlags != "S/SA" {
		s += " flags " + r.TCPFlags
	}

	// ICMP type
	if (r.Protocol == ProtoICMP || r.Protocol == ProtoICMP6) && r.ICMPType != "" {
		if r.Protocol == ProtoICMP6 {
			s += " icmp6-type " + r.ICMPType
		} else {
			s += " icmp-type " + r.ICMPType
		}
	}

	// Tagged
	if r.Tagged != "" {
		s += " tagged " + r.Tagged
	}

	// Tag
	if r.Tag != "" {
		s += " tag " + r.Tag
	}

	// Probability
	if r.Probability != nil && *r.Probability < 100 {
		s += fmt.Sprintf(" probability %d%%", *r.Probability)
	}

	// Once
	if r.Once {
		s += " once"
	}

	// State options (only for pass rules)
	if r.State != nil && r.Action == ActionPass {
		st := r.State
		if st.Mode == StateModeNone {
			s += " no state"
		} else {
			var opts []string
			if st.MaxStates != nil {
				opts = append(opts, fmt.Sprintf("max %d", *st.MaxStates))
			}
			if st.MaxSrcConn != nil {
				opts = append(opts, fmt.Sprintf("max-src-conn %d", *st.MaxSrcConn))
			}
			if st.MaxSrcConnRate != nil {
				opts = append(opts, fmt.Sprintf("max-src-conn-rate %d/%d", st.MaxSrcConnRate.Count, st.MaxSrcConnRate.Seconds))
			}
			if st.Overload != "" {
				overloadOpt := fmt.Sprintf("overload <%s>", st.Overload)
				if st.FlushGlobal {
					overloadOpt += " flush global"
				}
				opts = append(opts, overloadOpt)
			}
			if st.Sloppy {
				opts = append(opts, "sloppy")
			}
			if st.Policy != "" {
				opts = append(opts, string(st.Policy))
			}

			var kw string
			switch st.Mode {
			case StateModeModulate:
				kw = "modulate state"
			case StateModeSynproxy:
				kw = "synproxy state"
			default:
				kw = "keep state"
			}

			if len(opts) > 0 || st.Mode != StateModeKeep {
				s += " " + kw
				if len(opts) > 0 {
					s += " (" + strings.Join(opts, ", ") + ")"
				}
			}
		}
	}

	// Priority
	if r.Prio != nil {
		s += fmt.Sprintf(" set prio %d", *r.Prio)
	}

	// Rtable
	if r.RTable != nil {
		s += fmt.Sprintf(" rtable %d", *r.RTable)
	}

	// Route-to
	if r.Gateway != "" {
		if addr := gatewayAddr(r.Gateway, m); addr != "" {
			s += " route-to " + addr
		}
	}

	// Reply-to
	if r.ReplyTo != "" {
		if addr := gatewayAddr(r.ReplyTo, m); addr != "" {
			s += " reply-to " + addr
		}
	}

	return s + label(LabelRule, r.ID)
}

func endpoint(e Endpoint, m *Model) string {
	not := ""
	if e.Not {
		not = "! "
	}

	switch e.Type {
	case EndpointAny:
		return "any"
	case EndpointSelf:
		return not + ifaceRef(e, m)
	case EndpointIface:
		return not + ifaceRef(e, m)
	case EndpointHost, EndpointNetwork:
		return not + e.Value
	case EndpointAlias:
		// Address aliases are pf tables. Writing a bare name instead
		// would turn a table lookup into a hostname lookup.
		return fmt.Sprintf("%s<%s>", not, e.Alias)
	default:
		return "any"
	}
}

// ifaceRef writes an interface reference with its modifiers, in
// parentheses when dynamic: $lan:network, ($wan), (egress:network:0).
func ifaceRef(e Endpoint, m *Model) string {
	ref := e.Group
	switch {
	case e.Type == EndpointSelf:
		ref = "self"
	case e.Iface != "":
		ref = "$" + e.Iface
	}
	if e.Part != PartAddress {
		ref += ":" + string(e.Part)
	}
	if e.NoAlias {
		ref += ":0"
	}
	if ifaceDynamic(e, m) {
		ref = "(" + ref + ")"
	}
	return ref
}

// ifaceDynamic reports whether an interface reference should follow
// address changes. Without parentheses pf resolves it once, when the
// ruleset loads.
func ifaceDynamic(e Endpoint, m *Model) bool {
	if e.Dynamic != nil {
		return *e.Dynamic
	}
	if e.Type == EndpointSelf {
		// self is every interface's addresses, so it follows them if any
		// can change. With no model to ask, keep the plain form.
		if m == nil {
			return false
		}
		for _, i := range m.Interfaces {
			if i.Enabled && (i.IPv4.Mode != IPv4Static || i.IPv6 == IPv6SLAAC) {
				return true
			}
		}
		return false
	}
	if e.Group != "" || m == nil {
		return true
	}
	for _, i := range m.Interfaces {
		if i.ID == e.Iface {
			return i.IPv4.Mode != IPv4Static || i.IPv6 == IPv6SLAAC
		}
	}
	return true
}

func proto(p Protocol) string {
	switch p {
	case ProtoAny, "":
		return ""
	case ProtoTCPUDP:
		return " proto { tcp udp }"
	default:
		return " proto " + string(p)
	}
}

func portExpr(spec string, m *Model) string {
	s := strings.TrimSpace(spec)
	if s == "" {
		return ""
	}

	// Alias reference
	if strings.HasPrefix(s, "alias:") {
		aliasName := s[6:]
		if m != nil {
			for _, a := range m.Firewall.Aliases {
				if a.Name == aliasName {
					return " port { " + strings.Join(a.Entries, " ") + " }"
				}
			}
		}
		return ""
	}

	// Comma-separated list
	if strings.Contains(s, ",") {
		ports := strings.Split(s, ",")
		var trimmed []string
		for _, p := range ports {
			if t := strings.TrimSpace(p); t != "" {
				trimmed = append(trimmed, t)
			}
		}
		return " port { " + strings.Join(trimmed, " ") + " }"
	}

	// The UI accepts 8000-8080 for a range; pf wants 8000:8080. Named
	// ports such as netbios-ssn keep their dash.
	if parts := strings.Split(s, "-"); len(parts) == 2 && isNumber(parts[0]) && isNumber(parts[1]) {
		s = parts[0] + ":" + parts[1]
	}

	return " port " + s
}

func gatewayAddr(id string, m *Model) string {
	if m == nil {
		return ""
	}
	for _, g := range m.Routing.Gateways {
		if g.ID == id {
			if g.Address == "dhcp" {
				if status, ok := GatewayStatuses[g.ID]; ok {
					return status.Address
				}
				return "0.0.0.0"
			}
			return g.Address
		}
	}
	return ""
}

// onClause writes model interfaces as $id and groups as-is.
func onClause(ifaces, groups []string) string {
	var parts []string
	for _, i := range ifaces {
		parts = append(parts, "$"+i)
	}
	parts = append(parts, groups...)
	switch len(parts) {
	case 0:
		return ""
	case 1:
		return " on " + parts[0]
	}
	return " on { " + strings.Join(parts, " ") + " }"
}

// quote writes s as a pf.conf quoted string. pf's lexer only treats a
// backslash specially before a quote, space, tab or newline, so escaping
// the quotes is enough for any string without backslashes or newlines;
// Go's %q escapes (\t, \x9b, \\) would reach pf as literal text.
// Strings that can't be quoted faithfully must be rejected before
// generation.
func quote(s string) string {
	return `"` + strings.ReplaceAll(s, `"`, `\"`) + `"`
}

// Every rule OPF generates is labelled with the model object it comes
// from, "opf:<kind>:<id>". Labels are what pfctl reports counters by
// (pfctl -s labels), what states can be killed by (pfctl -k label), and
// the only per-rule text that reaches the kernel, so they're how live
// data is matched back to the model. A rule that pf expands into several
// shares its label, and so do its counters. Descriptions are written as
// comments above the rule instead: they're free text, and a label is
// at most 63 bytes, expands macros such as $if, and changes the loaded
// ruleset whenever it's edited.
const (
	LabelRule    = "rule"         // a firewall rule, by id
	LabelForward = "forward"      // a port forward and its reflection rules, by id
	LabelNAT     = "nat"          // an outbound NAT rule, by id
	LabelAutoNAT = "auto-nat"     // automatic outbound NAT, by inside interface id
	LabelBuiltin = "builtin"      // OPF's own rules, by name
	LabelSplit   = "split-tunnel" // limits on a tunnel's split-tunnel peers, by interface id
)

const labelPrefix = "opf:"

// labelIDRE is what an id in a label may be; Validate holds rule, port
// forward and NAT ids to it. With the longest kind that's 45 bytes, in
// PF_RULE_LABEL_SIZE's 63.
var labelIDRE = regexp.MustCompile(`^[A-Za-z0-9_-]{1,32}$`)

// Label is the label OPF gives the rules generated for an object.
func Label(kind, id string) string { return labelPrefix + kind + ":" + id }

// ParseLabel splits one of OPF's labels.
func ParseLabel(l string) (kind, id string, ok bool) {
	rest, found := strings.CutPrefix(l, labelPrefix)
	if !found {
		return "", "", false
	}
	kind, id, found = strings.Cut(rest, ":")
	switch kind {
	case LabelRule, LabelForward, LabelNAT, LabelAutoNAT, LabelBuiltin, LabelSplit:
	default:
		return "", "", false
	}
	return kind, id, found && labelIDRE.MatchString(id)
}

// label is the label clause for an object, or nothing for an id that
// can't be one (only possible for models that haven't been validated,
// such as a rule being previewed).
func label(kind, id string) string {
	if !labelIDRE.MatchString(id) {
		return ""
	}
	return " label " + quote(Label(kind, id))
}

// comment writes a description as a pf.conf comment line. pf's lexer
// joins a line ending in a backslash to the next one, even in a comment,
// so trailing backslashes are dropped (Validate rejects backslashes in
// descriptions anyway), as are line breaks.
func comment(s string) string {
	s = strings.Map(func(r rune) rune {
		if unicode.IsControl(r) {
			return ' '
		}
		return r
	}, s)
	s = strings.TrimRight(s, "\\ ")
	if s == "" {
		return ""
	}
	return "# " + s
}

// GenerateNATRule converts a NAT rule to pf.conf syntax.
func GenerateNATRule(n *NATRule, m *Model) string {
	return natRule(n, m, label(LabelNAT, n.ID))
}

// NoNATTag marks traffic an outbound NAT exception keeps untranslated.
// pf has no "no nat" any more, and ending evaluation early (pass out
// quick) would also skip the user's outbound rules, so exceptions tag
// the traffic and every nat-to rule on that interface leaves tagged
// traffic alone. A packet has one tag, so the exception replaces a tag
// an earlier rule set on the same traffic. Validate reserves the name.
const NoNATTag = "opf_nonat"

// natExceptions reports whether traffic out of iface can be excepted
// from NAT: manual exceptions only apply outside automatic mode.
func natExceptions(m *Model, iface string) bool {
	if m == nil || m.Firewall.OutboundNAT.Mode == NATModeAuto {
		return false
	}
	for _, n := range m.Firewall.OutboundNAT.Rules {
		if n.Enabled && n.Iface == iface && n.Translation.Type == TranslationNone {
			return true
		}
	}
	return false
}

func natRule(n *NATRule, m *Model, label string) string {
	hosts := fmt.Sprintf("on $%s inet from %s to %s",
		n.Iface, endpoint(n.Source, m), endpoint(n.Destination, m))

	if n.Translation.Type == TranslationNone {
		return "match out " + hosts + " tag " + NoNATTag + label
	}

	s := "match out " + hosts
	if natExceptions(m, n.Iface) {
		s += " ! tagged " + NoNATTag
	}
	if n.Translation.Type == TranslationIfaddr {
		s += fmt.Sprintf(" nat-to ($%s:0)", n.Iface)
	} else {
		s += " nat-to " + n.Translation.Value
	}

	if n.Pool != "" {
		s += " " + string(n.Pool)
	}
	if n.StaticPort {
		s += " static-port"
	}

	return s + label
}

// AutomaticNAT generates NAT rules for internal networks to WANs.
func AutomaticNAT(m *Model) []NATRule {
	wans := []Iface{}
	for _, i := range m.Interfaces {
		if i.Enabled && i.Role == RoleWAN {
			wans = append(wans, i)
		}
	}

	var rules []NATRule

	for _, w := range wans {
		// Every inside network, however it's addressed: the source is an
		// interface reference, so DHCP-addressed ones get parentheses.
		for _, i := range m.Interfaces {
			if !i.Enabled || i.Role == RoleWAN || i.IPv4.Mode == IPv4None {
				continue
			}
			rules = append(rules, NATRule{
				ID:          fmt.Sprintf("auto-%s-%s", w.ID, i.ID),
				Enabled:     true,
				Iface:       w.ID,
				Source:      Endpoint{Type: EndpointIface, Iface: i.ID, Part: PartNetwork},
				Destination: Endpoint{Type: EndpointAny},
				Translation: Translation{Type: TranslationIfaddr},
				StaticPort:  false,
				Description: fmt.Sprintf("Automatic: %s to %s", i.Name, w.Name),
			})
		}
	}

	return rules
}

// GeneratePortForward converts a port forward to pf.conf rules.
func GeneratePortForward(f *PortForward, m *Model) []string {
	log := ""
	if f.Log {
		log = " log"
	}
	from := endpoint(f.Source, m)
	// Built-in references follow the same rule as user rules: in
	// parentheses when the interface's address can change. Translation
	// targets (nat-to) are always in parentheses, as pf.conf(5) advises.
	public := endpoint(ifaceAddr(f.Iface), m)
	lbl := label(LabelForward, f.ID)

	lines := []string{
		fmt.Sprintf("pass in%s quick on $%s%s from %s to %s port %s rdr-to %s port %s%s",
			log, f.Iface, proto(f.Protocol), from, public, f.ExternalPort, f.Target, f.TargetPort, lbl),
	}

	if f.Reflection {
		for _, i := range insideIfaces(m) {
			inside := endpoint(Endpoint{Type: EndpointIface, Iface: i.ID, Part: PartNetwork}, m)
			lines = append(lines,
				fmt.Sprintf("pass in quick on $%s%s from %s to %s port %s rdr-to %s port %s%s",
					i.ID, proto(f.Protocol), inside, public, f.ExternalPort, f.Target, f.TargetPort, lbl),
				fmt.Sprintf("match out on $%s%s from %s to %s port %s nat-to ($%s)%s",
					i.ID, proto(f.Protocol), inside, f.Target, f.TargetPort, i.ID, lbl),
			)
		}
	}

	return lines
}

func staticIfaces(m *Model) []Iface {
	var result []Iface
	for _, i := range m.Interfaces {
		if i.Enabled && i.IPv4.Mode == IPv4Static && i.IPv4.Address != "" && i.IPv4.Prefix != nil {
			result = append(result, i)
		}
	}
	return result
}

// isFloating returns true if the rule applies to multiple or no interfaces.
// ifaceAddr is the addresses of a model interface.
func ifaceAddr(id string) Endpoint { return Endpoint{Type: EndpointIface, Iface: id} }

// insideIfaces are the enabled LAN and optional interfaces with IPv4,
// however they're addressed.
func insideIfaces(m *Model) []Iface {
	var out []Iface
	if m == nil {
		return out
	}
	for _, i := range m.Interfaces {
		if i.Enabled && (i.Role == RoleLAN || i.Role == RoleOPT) && i.IPv4.Mode != IPv4None {
			out = append(out, i)
		}
	}
	return out
}

func isFloating(r *Rule) bool {
	return len(r.Interfaces) != 1 || len(r.Groups) > 0
}

// GeneratePfRuleset generates the full pf.conf as a list of lines with origins.
func GeneratePfRuleset(m *Model) []PfLine {
	var lines []PfLine
	add := func(text string, origin *Origin) {
		lines = append(lines, PfLine{Text: text, Origin: origin})
	}
	blank := func() {
		lines = append(lines, PfLine{Text: ""})
	}
	// described adds an object's rules with its description above them.
	described := func(description string, origin *Origin, rules ...string) {
		if c := comment(description); c != "" {
			add(c, origin)
		}
		for _, r := range rules {
			add(r, origin)
		}
	}

	fw := m.Firewall
	o := fw.Options
	ifaces := []Iface{}
	for _, i := range m.Interfaces {
		if i.Enabled {
			ifaces = append(ifaces, i)
		}
	}

	var wan, lan *Iface
	for i := range ifaces {
		if ifaces[i].Role == RoleWAN && wan == nil {
			wan = &ifaces[i]
		}
		if ifaces[i].Role == RoleLAN && lan == nil {
			lan = &ifaces[i]
		}
	}

	settings := &Origin{Label: "Firewall settings", To: "/firewall/settings"}
	custom := &Origin{Label: "Custom pf", To: "/firewall/ruleset"}

	add(header, nil)
	blank()

	// Interfaces
	add("# Interfaces", nil)
	for _, i := range ifaces {
		add(fmt.Sprintf("%s = \"%s\"", i.ID, i.Device), &Origin{Label: fmt.Sprintf("Interface %s", i.Name), To: fmt.Sprintf("/interfaces/%s", i.ID)})
	}
	blank()

	// Aliases
	add("# Aliases", nil)
	for _, a := range fw.Aliases {
		if a.Type == AliasPorts {
			continue
		}
		origin := &Origin{Label: fmt.Sprintf("Alias %s", a.Name), To: "/firewall/aliases"}
		switch a.Type {
		case AliasTable:
			add(fmt.Sprintf("table <%s> persist", a.Name), origin)
		case AliasURL:
			refreshHours := 24
			if a.RefreshHours != nil {
				refreshHours = *a.RefreshHours
			}
			add(fmt.Sprintf("table <%s> persist file \"/var/opf/tables/%s\"\t# refreshed every %dh from %s", a.Name, a.Name, refreshHours, a.URL), origin)
		default:
			add(fmt.Sprintf("table <%s> const { %s }", a.Name, strings.Join(a.Entries, " ")), origin)
		}
	}
	if wan != nil && wan.BlockBogons {
		add("table <bogons> const { 0.0.0.0/8 100.64.0.0/10 127.0.0.0/8 169.254.0.0/16 192.0.0.0/24 198.18.0.0/15 224.0.0.0/3 }", &Origin{Label: "WAN protection", To: fmt.Sprintf("/interfaces/%s", wan.ID)})
	}
	if wan != nil && wan.BlockPrivate {
		add("table <private> const { 10.0.0.0/8 172.16.0.0/12 192.168.0.0/16 }", &Origin{Label: "WAN protection", To: fmt.Sprintf("/interfaces/%s", wan.ID)})
	}
	split := splitPeers(m)
	if len(split) > 0 {
		add(fmt.Sprintf("table <%s> const { %s }", LocalTable, strings.Join(LocalNetworks(m, true), " ")),
			&Origin{Label: "WireGuard: your networks", To: "/services/wireguard"})
	}
	blank()

	// Options
	add("# Options", nil)
	add(fmt.Sprintf("set block-policy %s", o.BlockPolicy), settings)
	add(fmt.Sprintf("set state-policy %s", o.StatePolicy), settings)
	add(fmt.Sprintf("set optimization %s", o.Optimization), settings)
	add(fmt.Sprintf("set limit states %d", o.MaxStates), settings)
	syncookies := string(o.Syncookies)
	if o.Syncookies == SyncookiesAdaptive {
		syncookies += " (start 25%, end 12%)"
	}
	add(fmt.Sprintf("set syncookies %s", syncookies), settings)
	add("set skip on lo", settings)
	if wan != nil {
		add(fmt.Sprintf("set loginterface $%s", wan.ID), settings)
	}
	for _, line := range strings.Split(fw.Custom.Options, "\n") {
		if strings.TrimSpace(line) != "" {
			add(line, custom)
		}
	}
	if o.Scrub.Enabled {
		var scrubOpts []string
		if o.Scrub.NoDf {
			scrubOpts = append(scrubOpts, "no-df")
		}
		if o.Scrub.RandomID {
			scrubOpts = append(scrubOpts, "random-id")
		}
		if o.Scrub.MaxMss != nil {
			scrubOpts = append(scrubOpts, fmt.Sprintf("max-mss %d", *o.Scrub.MaxMss))
		}
		add(fmt.Sprintf("match in all scrub (%s)", strings.Join(scrubOpts, " ")), settings)
	}
	blank()

	// Outbound NAT
	add("# Outbound NAT", nil)
	natOrigin := &Origin{Label: "Outbound NAT", To: "/firewall/nat/outbound"}

	var manual, auto []NATRule
	if fw.OutboundNAT.Mode != NATModeAuto {
		for _, r := range fw.OutboundNAT.Rules {
			if r.Enabled {
				manual = append(manual, r)
			}
		}
	}
	if fw.OutboundNAT.Mode != NATModeManual {
		auto = AutomaticNAT(m)
	}

	// Exceptions first, so their tag is set before any nat-to rule looks.
	for _, n := range manual {
		if n.Translation.Type == TranslationNone {
			described(n.Description, natOrigin, GenerateNATRule(&n, m))
		}
	}
	// Automatic NAT
	for i := range auto {
		described(auto[i].Description, natOrigin, natRule(&auto[i], m, label(LabelAutoNAT, auto[i].Source.Iface)))
	}
	// Manual NAT (non-exceptions)
	for _, n := range manual {
		if n.Translation.Type != TranslationNone {
			described(n.Description, natOrigin, GenerateNATRule(&n, m))
		}
	}
	blank()

	// Defaults
	add("# Defaults", nil)
	if o.LogDefaultBlock {
		add("block log all"+label(LabelBuiltin, "default-block"), &Origin{Label: "Default block", To: "/firewall/settings"})
	} else {
		add("block all"+label(LabelBuiltin, "default-block"), &Origin{Label: "Default block", To: "/firewall/settings"})
	}
	// Outbound traffic passes unless a later rule says otherwise. Not
	// quick: a quick pass here would end evaluation before every user
	// rule, so outbound blocks and match rules (set prio, tags) would
	// never be reached.
	add("pass out inet"+label(LabelBuiltin, "self-out"), &Origin{Label: "This firewall's own traffic", To: "/firewall/settings"})
	add("pass out inet6"+label(LabelBuiltin, "self-out"), &Origin{Label: "This firewall's own traffic", To: "/firewall/settings"})
	if lan != nil {
		described("Anti-lockout: the web UI and SSH stay reachable from the LAN", &Origin{Label: "Anti-lockout", To: fmt.Sprintf("/interfaces/%s", lan.ID)},
			fmt.Sprintf("pass in quick on $%s proto tcp to %s port { 443 22 }%s", lan.ID, endpoint(ifaceAddr(lan.ID), m), label(LabelBuiltin, "anti-lockout")))
	}
	if wan != nil && wan.BlockPrivate {
		described("Block private networks", &Origin{Label: "WAN protection", To: fmt.Sprintf("/interfaces/%s", wan.ID)},
			fmt.Sprintf("block in log quick on $%s from <private>%s", wan.ID, label(LabelBuiltin, "block-private")))
	}
	if wan != nil && wan.BlockBogons {
		described("Block bogon networks", &Origin{Label: "WAN protection", To: fmt.Sprintf("/interfaces/%s", wan.ID)},
			fmt.Sprintf("block in log quick on $%s from <bogons>%s", wan.ID, label(LabelBuiltin, "block-bogons")))
	}
	blank()

	// Devices told to send only local traffic through their tunnel may
	// only reach local networks, whatever their own configuration says.
	// Before every user rule, so no pass rule can widen it.
	if len(split) > 0 {
		add("# WireGuard devices limited to your networks", nil)
		for _, t := range split {
			var names, addrs []string
			for _, p := range t.peers {
				names = append(names, p.Name)
				addrs = append(addrs, p.Address)
			}
			from := addrs[0]
			if len(addrs) > 1 {
				from = "{ " + strings.Join(addrs, " ") + " }"
			}
			described(fmt.Sprintf("%s: %s", t.iface.Name, strings.Join(names, ", ")), &Origin{Label: "WireGuard: " + t.iface.Name, To: "/services/wireguard/" + t.iface.ID},
				fmt.Sprintf("block in log quick on $%s inet from %s to ! <%s>%s", t.iface.ID, from, LocalTable, label(LabelSplit, t.iface.ID)))
		}
		blank()
	}

	// Port forwards
	var forwards []PortForward
	for _, f := range fw.Forwards {
		if !f.Enabled {
			continue
		}
		// Check if interface exists
		for _, i := range ifaces {
			if i.ID == f.Iface {
				forwards = append(forwards, f)
				break
			}
		}
	}
	if len(forwards) > 0 {
		add("# Port forwards", nil)
		for i := range forwards {
			described(forwards[i].Description, &Origin{Label: fmt.Sprintf("Port forward: %s", forwards[i].Description), To: "/firewall/nat"},
				GeneratePortForward(&forwards[i], m)...)
		}
		blank()
	}

	// Custom before filter
	if strings.TrimSpace(fw.Custom.BeforeFilter) != "" {
		add("# Custom rules (before)", nil)
		for _, line := range strings.Split(fw.Custom.BeforeFilter, "\n") {
			add(line, custom)
		}
		blank()
	}

	// Floating rules
	var floating []Rule
	for i := range fw.Rules {
		if fw.Rules[i].Enabled && isFloating(&fw.Rules[i]) {
			floating = append(floating, fw.Rules[i])
		}
	}
	if len(floating) > 0 {
		add("# Floating rules", nil)
		for i := range floating {
			described(floating[i].Description, &Origin{Label: fmt.Sprintf("Rule: %s", floating[i].Description), To: "/firewall/rules/floating"}, GenerateRule(&floating[i], m))
		}
		blank()
	}

	// Per-interface rules
	for _, iface := range ifaces {
		var ifaceRules []Rule
		for i := range fw.Rules {
			r := &fw.Rules[i]
			if r.Enabled && !isFloating(r) && r.Interfaces[0] == iface.ID {
				ifaceRules = append(ifaceRules, *r)
			}
		}
		if len(ifaceRules) == 0 {
			continue
		}
		add(fmt.Sprintf("# %s rules", iface.Name), nil)
		for i := range ifaceRules {
			described(ifaceRules[i].Description, &Origin{Label: fmt.Sprintf("Rule: %s", ifaceRules[i].Description), To: fmt.Sprintf("/firewall/rules/%s", iface.ID)}, GenerateRule(&ifaceRules[i], m))
		}
		blank()
	}

	// Custom after filter
	if strings.TrimSpace(fw.Custom.AfterFilter) != "" {
		add("# Custom rules (after)", nil)
		for _, line := range strings.Split(fw.Custom.AfterFilter, "\n") {
			add(line, custom)
		}
		blank()
	}

	return lines
}

// GeneratePfConf generates the full pf.conf as a string.
func GeneratePfConf(m *Model) string {
	lines := GeneratePfRuleset(m)
	var parts []string
	for _, l := range lines {
		parts = append(parts, l.Text)
	}
	return strings.Join(parts, "\n")
}

// GenerateHostnameIf generates /etc/hostname.<device> content.
func GenerateHostnameIf(i *Iface, m *Model) string {
	var lines []string
	lines = append(lines, header)

	if i.VLAN != nil {
		lines = append(lines, fmt.Sprintf("vnetid %d parent %s", i.VLAN.Tag, i.VLAN.Parent))
	}

	if wg := i.WireGuard; i.Role == RoleVPN && wg != nil {
		lines = append(lines, "wgkey <private key stored by OPF>", fmt.Sprintf("wgport %d", wg.ListenPort))
		for _, p := range wg.Peers {
			aips := []string{fmt.Sprintf("wgaip %s", p.Address)}
			for _, net := range p.Networks {
				aips = append(aips, fmt.Sprintf("wgaip %s", net))
			}
			line := fmt.Sprintf("wgpeer %s %s", p.PublicKey, strings.Join(aips, " "))
			if host, port, err := net.SplitHostPort(p.Endpoint); err == nil {
				line += fmt.Sprintf(" wgendpoint %s %s", host, port)
			}
			if p.Keepalive != nil {
				line += fmt.Sprintf(" wgpka %d", *p.Keepalive)
			}
			line += fmt.Sprintf(" wgdescr \"%s\"", p.Name)
			lines = append(lines, line)
		}
	}

	lines = append(lines, fmt.Sprintf("description \"%s\"", i.Name))

	if i.MTU != nil {
		lines = append(lines, fmt.Sprintf("mtu %d", *i.MTU))
	}

	if i.IPv4.Mode == IPv4DHCP {
		lines = append(lines, "inet autoconf")
	}
	if i.IPv4.Mode == IPv4Static && i.IPv4.Address != "" {
		lines = append(lines, fmt.Sprintf("inet %s/%d", i.IPv4.Address, *i.IPv4.Prefix))
	}
	if i.IPv6 == IPv6SLAAC {
		lines = append(lines, "inet6 autoconf")
	}

	if i.Enabled {
		lines = append(lines, "up")
	} else {
		lines = append(lines, "down")
	}

	// Static routes through this interface
	for _, r := range m.Routing.Routes {
		if !r.Enabled {
			continue
		}
		for _, g := range m.Routing.Gateways {
			if g.ID == r.Gateway && g.Iface == i.ID && g.Address != "dhcp" {
				lines = append(lines, fmt.Sprintf("!route -q add -net %s %s\t# %s", r.Network, g.Address, r.Description))
				break
			}
		}
	}

	return strings.Join(lines, "\n") + "\n"
}

// GenerateDHCPdConf generates /etc/dhcpd.conf content.
func GenerateDHCPdConf(m *Model) string {
	var lines []string
	lines = append(lines, header, "", fmt.Sprintf("option domain-name \"%s\";", m.System.Domain), "")

	for _, s := range m.DHCP {
		if !s.Enabled {
			continue
		}
		var iface *Iface
		for i := range m.Interfaces {
			if m.Interfaces[i].ID == s.Iface {
				iface = &m.Interfaces[i]
				break
			}
		}
		if iface == nil || iface.IPv4.Mode != IPv4Static || iface.IPv4.Address == "" || iface.IPv4.Prefix == nil {
			continue
		}

		dns := iface.IPv4.Address
		if s.DNS == DNSModeCustom {
			dns = strings.Join(s.DNSServers, ", ")
		}

		lines = append(lines, fmt.Sprintf("# %s", iface.Name))
		lines = append(lines, fmt.Sprintf("subnet %s netmask %s {", networkAddr(iface.IPv4.Address, *iface.IPv4.Prefix), netmask(*iface.IPv4.Prefix)))
		lines = append(lines, fmt.Sprintf("\toption routers %s;", iface.IPv4.Address))
		lines = append(lines, fmt.Sprintf("\toption domain-name-servers %s;", dns))
		lines = append(lines, fmt.Sprintf("\trange %s %s;", s.RangeStart, s.RangeEnd))
		lines = append(lines, fmt.Sprintf("\tdefault-lease-time %d;", s.LeaseHours*3600))

		for _, r := range s.Reservations {
			lines = append(lines, fmt.Sprintf("\thost %s {", r.Hostname))
			lines = append(lines, fmt.Sprintf("\t\thardware ethernet %s;", r.MAC))
			lines = append(lines, fmt.Sprintf("\t\tfixed-address %s;", r.IP))
			lines = append(lines, "\t}")
		}

		lines = append(lines, "}", "")
	}

	return strings.Join(lines, "\n")
}

// GenerateUnboundConf generates /var/unbound/etc/unbound.conf content.
func GenerateUnboundConf(m *Model) string {
	d := m.DNS
	inside := staticIfaces(m)
	insideNonWAN := []Iface{}
	for _, i := range inside {
		if i.Role != RoleWAN {
			insideNonWAN = append(insideNonWAN, i)
		}
	}

	var lines []string
	lines = append(lines, header, "", "server:", "\tinterface: 127.0.0.1")

	for _, i := range insideNonWAN {
		lines = append(lines, fmt.Sprintf("\tinterface: %s", i.IPv4.Address))
	}

	lines = append(lines, "\taccess-control: 127.0.0.0/8 allow")
	for _, i := range insideNonWAN {
		lines = append(lines, fmt.Sprintf("\taccess-control: %s/%d allow", networkAddr(i.IPv4.Address, *i.IPv4.Prefix), *i.IPv4.Prefix))
	}

	lines = append(lines, "\thide-identity: yes", "\thide-version: yes")

	if d.DNSSEC {
		lines = append(lines, "\tauto-trust-anchor-file: \"/var/unbound/db/root.key\"", "\tval-log-level: 2")
	}

	lines = append(lines, fmt.Sprintf("\tlocal-zone: \"%s.\" static", m.System.Domain))

	for _, o := range d.Overrides {
		lines = append(lines, fmt.Sprintf("\tlocal-data: \"%s.%s. IN A %s\"", o.Host, o.Domain, o.IP))
	}

	if d.RegisterReservations {
		for _, s := range m.DHCP {
			for _, r := range s.Reservations {
				lines = append(lines, fmt.Sprintf("\tlocal-data: \"%s.%s. IN A %s\"", r.Hostname, m.System.Domain, r.IP))
			}
		}
	}

	// Dynamic leases are added at runtime, over a control socket that
	// only root can use.
	if d.RegisterDynamicLeases {
		lines = append(lines, "", "remote-control:", "\tcontrol-enable: yes", "\tcontrol-interface: /var/run/unbound.sock")
	}

	if d.Mode == ResolverModeForward {
		lines = append(lines, "", "forward-zone:", "\tname: \".\"")
		if d.ForwardTLS {
			lines = append(lines, "\tforward-tls-upstream: yes")
		}
		for _, f := range d.Forwarders {
			if d.ForwardTLS {
				lines = append(lines, fmt.Sprintf("\tforward-addr: %s@853", f))
			} else {
				lines = append(lines, fmt.Sprintf("\tforward-addr: %s", f))
			}
		}
	}

	return strings.Join(lines, "\n") + "\n"
}

// GenerateFiles generates all config files from the model.
func GenerateFiles(m *Model) []GeneratedFile {
	files := []GeneratedFile{
		{Path: "/etc/myname", Content: fmt.Sprintf("%s.%s\n", m.System.Hostname, m.System.Domain)},
		{Path: "/etc/ntpd.conf", Content: header + "\n" + ntpdConf(m.System.NTPServers)},
		{Path: "/etc/pf.conf", Content: GeneratePfConf(m)},
		{Path: "/etc/dhcpd.conf", Content: GenerateDHCPdConf(m)},
		{Path: "/var/unbound/etc/unbound.conf", Content: GenerateUnboundConf(m)},
		{Path: "/etc/rc.conf.local", Content: GenerateRcConfLocal(m)},
	}

	// Default gateway
	for _, g := range m.Routing.Gateways {
		if g.ID == m.Routing.DefaultGateway && g.Address != "dhcp" {
			files = append(files, GeneratedFile{Path: "/etc/mygate", Content: g.Address + "\n"})
			break
		}
	}

	// Interface files
	for i := range m.Interfaces {
		files = append(files, GeneratedFile{
			Path:    fmt.Sprintf("/etc/hostname.%s", m.Interfaces[i].Device),
			Content: GenerateHostnameIf(&m.Interfaces[i], m),
		})
	}

	return files
}

func ntpdConf(servers []string) string {
	var lines []string
	for _, s := range servers {
		lines = append(lines, fmt.Sprintf("servers %s", s))
	}
	return strings.Join(lines, "\n") + "\n"
}

func networkAddr(address string, prefix int) string {
	ip := net.ParseIP(address)
	if ip == nil {
		return address
	}
	mask := net.CIDRMask(prefix, 32)
	return ip.Mask(mask).String()
}

func netmask(prefix int) string {
	mask := net.CIDRMask(prefix, 32)
	return net.IP(mask).String()
}

// LocalTable is the pf table of LocalNetworks, generated when a tunnel
// has split-tunnel peers.
const LocalTable = "opf_local"

// LocalNetworks is what counts as "your networks" for a split-tunnel
// peer: every enabled inside interface's network, every network behind
// a site-to-site peer, and every static route's. A peer's configuration
// sends these into its tunnel, and pf lets it reach nothing else. With
// dynamic, an inside interface addressed by DHCP is included as
// $id:network, which pf resolves when it loads the rules; a device's
// configuration can only list fixed networks, so without it they're
// left out.
func LocalNetworks(m *Model, dynamic bool) []string {
	var out []string
	seen := map[string]bool{}
	add := func(n string) {
		if !seen[n] {
			seen[n] = true
			out = append(out, n)
		}
	}
	for i := range m.Interfaces {
		f := &m.Interfaces[i]
		if !f.Enabled || f.Role == RoleWAN {
			continue
		}
		if n, ok := ifaceNet(f); ok {
			add(n.String())
		} else if dynamic && f.IPv4.Mode == IPv4DHCP {
			add("$" + f.ID + ":network")
		}
	}
	for _, t := range m.Tunnels() {
		if !t.Enabled {
			continue
		}
		for _, p := range t.WireGuard.Peers {
			for _, n := range p.Networks {
				add(n)
			}
		}
	}
	for _, r := range m.Routing.Routes {
		if r.Enabled {
			add(r.Network)
		}
	}
	return out
}

type splitTunnel struct {
	iface *Iface
	peers []Peer
}

// splitPeers returns the enabled tunnels with split-tunnel peers.
func splitPeers(m *Model) []splitTunnel {
	var out []splitTunnel
	for _, t := range m.Tunnels() {
		if !t.Enabled {
			continue
		}
		var peers []Peer
		for _, p := range t.WireGuard.Peers {
			if p.ClientRoutes == ClientRoutesSplit {
				peers = append(peers, p)
			}
		}
		if len(peers) > 0 {
			out = append(out, splitTunnel{t, peers})
		}
	}
	return out
}
